### ISSUE TITLE
Não está buscando pela codPostagemRelacionada

### ISSUE THREAD

**Issue by andre991** [AppCivicoPlataforma/AppCivico#10]
no endpoint /rest/postagens/timeline o parametro de busca codPostagemRelacionada não está funcionando, ele retorna 204- No Content, mas existe esta postagem devidamente relacionada.

**Comment by monilouise** [comment]
Boa tarde andre991,

O problema encontra-se solucionado - favor verificar novamente.

Obrigada por ter reportado!

**Comment by andre991** [comment]
Obrigado monilouise, verificado! Está tudo certo.

**Comment by monilouise** [comment]
Resolvido.
