### ISSUE TITLE
Fornecer a API em HTTPS também

### ISSUE THREAD

**Issue by caduvieira** [AppCivicoPlataforma/AppCivico#11]
Fornecer a API em SSL utilizando algum certificado válido para os browsers e SOs.

**Comment by AppCivicoPlataforma** [comment]
Olá @caduvieira ,

Não há previsão de uso de certificado digital (e consequentemente SSL) para o [Desafio de Aplicativos Cívicos](url).

Quando da conclusão do concurso será fornecido um ambiente de produção no qual será provido acesso com SSL.

[]´s

Equipe AppCívico do TCU
