### ISSUE TITLE
Cadastrar Usuário - Não me retorna o erro no padrão dos outros endpoints.

### ISSUE THREAD

**Issue by andre991** [AppCivicoPlataforma/AppCivico#12]
Quando cadastro um usuário e o mesmo já existe ou está desativado ele me retorna 400, o 400 é representado como Bad Request solicito há vocês colocar este erro no padrão dos outros endpoints, pois assim fica difícil de tratar a requisição sendo que os endpoints(POST - /rest/pessoas) não tem um padrão de retorno de erros como os outros.
{
  "dadosTecnicos": "string",
  "mensagens": [
    {
      "texto": "string"
    }
  ],
  "reasonPhrase": "string",
  "siglaErro": "string",
  "statusCode": 0,
  "url": "string"
}

Obrigado.

**Comment by SkiaBr23** [comment]
@andre991,

Estamos analisando a melhor forma de solucionar esse problema. Aviso por aqui quando publicarmos alguma alteração.

Obrigado pela sugestao!

**Comment by andre991** [comment]
@SkiaBr23 

Ok. Obrigado, estou no aguardo.

**Comment by SkiaBr23** [comment]
@andre991,

O endpoint já está retornando a mensagem de erro correta, utilizando o padrão de erro.  O _Response Body_ é enviado da seguinte forma:

Erro - 400 - "Usuário já cadastrado ou desativado"

Favor testar via [Swagger](http://mobile-aceite.tcu.gov.br/appCivicoRS/swagger/index.html?url=/appCivicoRS/v2/api-docs#!/pessoas/cadastrarPessoaUsingPOST) e caso isso tenha solucionado seu problema, aguardamos feedback.

[]'s
