### ISSUE TITLE
Parametros para pesquisa - GET /rest/escolas/latitude/{latitude}/longitude/{longitude}/raio/{raio}

### ISSUE THREAD

**Issue by geraugu** [AppCivicoPlataforma/AppCivico#13]
Prezados,

favor acrescentar os seguintes parâmetros no serviço GET /rest/escolas/latitude/{latitude}/longitude/{longitude}/raio/{raio}
- rede
- situacaoFuncionamento

**Comment by andre991** [comment]
se eu nao me engano, a situação de funcionamento já é filtrada quando você faz a requisição, afinal não faz sentido você trazer uma escola desativada. ;)

**Comment by nmschumacher** [comment]
Olá, @geraugu

provavelmente amanhã de manhã estes parâmetros serão acrescentados.

**Comment by SkiaBr23** [comment]
@geraugu,

Foram adicionados os parâmetros requisitados. Estão no formato de parâmetros opcionais, então sugiro verificar via [Swagger](http://mobile-aceite.tcu.gov.br/appCivicoRS/swagger/index.html?url=/nossaEscolaRS/v2/api-docs#!/escolas/recuperarEscolasUsingGET) a estrutura da URL de requisição. 

Obrigado pela sugestão.
