### ISSUE TITLE
Atualização de dados - recurso (GET) /rest/estabelecimentos/latitude/{latitude}/longitude/{longitude}/raio/{raio}

### ISSUE THREAD

**Issue by ragulhari** [AppCivicoPlataforma/AppCivico#14]
Bom dia, gostaria de uma informação talvez não pertinente a esse fórum, mas se possível agradeço se conseguirem responder.

Usando o recurso **(GET) /rest/estabelecimentos/latitude/{latitude}/longitude/{longitude}/raio/{raio}** em alguns municípios, percebi que a informação de latitude e longitude estão vindo repetidos em todos os estabelecimentos (por exemplo Bauru-SP). Entendo que é um problema de dados, porque outros municípios funcionam ok.

Gostaria de saber qual órgão entrar em contato para verificar a possibilidade de atualização dessas informações, se alguém puder ajudar agradeço.

**Comment by LucianoPAlmeida** [comment]
Olá @ragulhari,
As bases que carregamos são dados do CNES, que por sua vez mantém uma base declarativa, ou seja, o próprio estabelecimento fornece esse dado. O que acontece é que muitas vezes o responsável por fornecer a informação não tem conhecimento e acaba só pesquisando no google, geralmente achando o ponto central da cidade, o que leva a terem vários estabelecimentos no mesmo ponto(geralmente centro da cidade, não sei se é o caso aí em Bauru). Outra possibilidade são estabelecimentos localizados no mesmo prédio, geralmente clínicas de saúde. Um dos grandes problemas de alguns dados abertos é que às vezes são inconsistentes. Sobre um orgão para relatar, acho que seria direto com o pessoal [CNES](http://cnes.datasus.gov.br/) pois nossas bases são atualizadas mensalmente de acordo com os dados deles.

Espero ter ajudado :)
Att. Equipe AppCivico
