### ISSUE TITLE
Problema ao fazer request Ajax POST /rest/pessoas

### ISSUE THREAD

**Issue by eduardobreno** [AppCivicoPlataforma/AppCivico#15]
Ao tentar fazer request com angular ou jquery, recebo a resposta do servidor:

> XMLHttpRequest cannot load http://mobile-aceite.tcu.gov.br/appCivicoRS/rest/pessoas. Request header field cache-control is not allowed by Access-Control-Allow-Headers in preflight response.

Ao adicionar o `Content-Type:applicaiton/json` os fws adicionam o:

> Access-Control-Request-Headers:content-type

Acredito que essa opção deva ser adicionar ao servidor para aceitar os headers.

**Comment by SkiaBr23** [comment]
@eduardobreno,

Vamos resolver esse problema em breve. Logo que for solucionado, aviso por aqui.

Obrigado pelo feedback!

**Comment by jrpacheco** [comment]
CORS!

**Comment by SkiaBr23** [comment]
@eduardobreno,
- Adicionamos o _header field_ 'cache-control' na lista de permitidos pelo servidor. Peço que faça um teste pra sabermos se o problema foi resolvido.
- A respeito do erro no 'content-type', por acaso você utilizou literalmente 
  
  > Content-Type:applicaiton/json
  
  No código? Pode ter ocorrido erro por esse _typo_ em 'application'.

Aguardo a resposta!

**Comment by eduardobreno** [comment]
@SkiaBr23 ,
Está escrito corretamente, foi na hora de escrever o issue q escrevi errado.
Em relação ao problema, ele persiste.

Eu percebi que eu colei a mensagem de erro errada na abertura do issue a correta seria essa:

> XMLHttpRequest cannot load http://mobile-aceite.tcu.gov.br/appCivicoRS/rest/pessoas. Request header field Content-Type is not allowed by Access-Control-Allow-Headers in preflight response.

Peço desculpas, mas o header seria o `Content-Type`  e não o `cache-control`.

Estou usando ionic com angular, quando testo no navegador chrome ele retorna esse erro, mas quando eu faço o build para android, ele funciona perfeitamente.

**Comment by SkiaBr23** [comment]
@eduardobreno,

Troquei para _Content-Type_. Pode testar novamente?

**Comment by eduardobreno** [comment]
@SkiaBr23  Funcionou, obrigado!

**Comment by eduardobreno** [comment]
Olá de novo,
ao tentar realizar a autenticação de um usuário, ao adicionar os headers `email`e `senha`, e fazer o request acontece o mesmo problema:

> XMLHttpRequest cannot load http://mobile-aceite.tcu.gov.br/appCivicoRS/rest/pessoas/autenticar. Request header field senha is not allowed by Access-Control-Allow-Headers in preflight response

O autenticar pede o email e senha no header, e acho q eles também devem ser adicionados igual ao Content-Type.
Sendo assim, para não ficar abrindo issues, acho que todos os headers que são solicitados nos endpoints devem ser adicionados as regras do servidor.

Peço isso devido do desenvolvimento e testes que estou realizando se realizar nos navegadores e só após isso faço o build para o device.

Grato desde de já.

**Comment by SkiaBr23** [comment]
@eduardobreno,

Vamos analisar todos os headers solicitados nos endpoints e provavelmente na segunda farei essa alteração.

**Comment by SkiaBr23** [comment]
@eduardobreno,

Foi publicada a alteração nos headers. Agora, incluímos todos os headers que os endpoints precisam. Pode testar novamente? Aguardo feedback!

**Comment by eduardobreno** [comment]
@SkiaBr23,
funcinonou, valeu!
