### ISSUE TITLE
Consulta de Estabelecimentos por especialidade

### ISSUE THREAD

**Issue by LoveraSantiago** [AppCivicoPlataforma/AppCivico#16]
Boa noite.

Penso ser relevante uma consulta de estabelecimentos de saúde por uma especialidade em questão.

**Comment by SkiaBr23** [comment]
@LoveraSantiago,

Obrigado pela sugestão! Estaremos implementando essa busca e vamos avisar por aqui quando for publicada.

**Comment by LoveraSantiago** [comment]
Oi Rafael tenho algumas perguntas que não sei bem onde localizar as respostas.

1 - Para mais sugestões coloco aqui mesmo ou abro outra issue?
2 - É possível acrescentar a distribuição de medicamentos por estabelecimento?
3 - Pesquisa de profissionais de certas categorias por região, municipio, geo-localização?
4 - Incluir campo de CNPJ para os estabelecimentos.

Obrigado pela resposta.

**Comment by SkiaBr23** [comment]
@LoveraSantiago,

1 - Sugestões de implementação ou problemas técnicos diferentes, de preferência outra issue.
2 - A base de remédios atualmente não possui relação de estabelecimentos de distribuição.
3 - Estamos testando a implementação da busca de especialidade por estabelecimento e logo que for finalizada passaremos para a busca por geo-localização.
4 - O campo de cnpj já foi incluído e a alteração será publicada em breve.

**Comment by LoveraSantiago** [comment]
Obrigado Rafael.

**Comment by nmschumacher** [comment]
@LoveraSantiago,

Está disponível o filtro de estabelecimentos por especialidade no serviço `GET - /rest/estabelecimentos`
Basta utilizar o campo opcional _especialidade_.

Para facilitar o uso deste filtro, veja a lista de [especialidades disponíveis](https://github.com/AppCivicoPlataforma/AppCivico/blob/master/EstabelecimentosAPI.md#especialidades-habilitadas-disponíveis) para busca.

A pesquisa de profissionais por localização geográfica ainda será implementada.

**Comment by LoveraSantiago** [comment]
Rafael novamente agradeço.

Existe alguma especie de dado financeiro em relação ao estabelecimento?

**Comment by AppCivicoPlataforma** [comment]
@LoveraSantiago,

A base de dados fornecida pelo [DataSus ](http://cnes.datasus.gov.br/), o Cadastro Nacional de Estabelecimentos de Saúde (CNES), não contém dados financeiros dos estabelecimentos. 

Ademais, solicito que crie uma nova issue para a busca de profissionais por localização geográfica. 

[]´s

Equipe do [Desafio de Aplicativos Cívicos](http://portal.tcu.gov.br/desafio-aplicativos-civicos/o-desafio/).
