### ISSUE TITLE
Consulta de grupos GET /rest/grupos/{codGrupo}

### ISSUE THREAD

**Issue by eduardobreno** [AppCivicoPlataforma/AppCivico#17]
Podemos criar grupos e subgrupos, mas ao consultar um grupo que é pai ele não retorna quem são os filhos, mas quando consultamos um que é filho ele retorna o pai.

Existe a possibilidade de retornar os grupos filhos associados ao grupo pai?
E realizar a busca de grupos por descrição e por aplicativo?

**Comment by SkiaBr23** [comment]
@eduardobreno,

Obrigado pela sugestão! Estamos finalizando a implementação dessas novas buscas e acredito que amanhã já estarão publicadas. Avisarei por aqui.

**Comment by thiagonunes-silva** [comment]
Seria possível fazer uma pesquisa bem genérica por grupos? Neste caso, o serviço poderia exigir sempre que o código do aplicativo fosse informado, mas aceitaria qualquer combinação dos outros atributos do grupo, como ocorre em outros casos. No meu aplicativo, estava pensando em utilizar 3 consultas de grupos: 1 - informar o grupo pai e obter todos os seus filhos; 2 - informar o COD_OBJETO e obter o grupo relacionado; 3 - informar o COD_TIPO_OBJETO e obter os grupos relacionados.

**Comment by nmschumacher** [comment]
@eduardobreno ,

O serviço de buscar os grupos filhos de um certo grupo já foi implementado e pode ser utilizado via
   `GET - /rest/grupos/subgrupos/{codGrupoPai}`

**Comment by eduardobreno** [comment]
@nmschumacher 
blz, agora é possível consultar os filhos de um grupo.

Quando a gente cadastra um grupo que já existe ele retorna `code 400 "grupo já cadastrado"` , seria bom se também retornasse o `codGrupo` ou disponibilizar uma busca por nome para não precisarmos cadastrar para obtermos o `codGrupo`.

**Comment by SkiaBr23** [comment]
@eduardobreno, 

Estamos desenvolvendo a sugestão de busca do @thiagonunes-silva  que inclui essa busca genérica de grupos.

**Comment by SkiaBr23** [comment]
@eduardobreno e @thiagonunes-silva,

Já está publicada a nova busca de grupos. Favor consultar seu funcionamento e parâmetros via Swagger.
A busca aceita o código do aplicativo, a descricao do grupo, código do objeto ou código do tipo de objeto. Peço que testem e retornem com feedback.

P.S: Grupos que não retornam o código do objeto ou do tipo de objeto, é devido a falta dessa informação na base de dados.

http://mobile-aceite.tcu.gov.br/appCivicoRS/swagger/index.html?url=/appCivicoRS/v2/api-docs#!/grupos/buscaGruposUsingGET

**Comment by eduardobreno** [comment]
Beleza, tudo certo..

**Comment by thiagonunes-silva** [comment]
Pessoal, quando eu estou fazendo a pesquisa de grupos informando o código do aplicativo, a descrição, o código do tipo de objeto e o código do objeto estou tomando um erro. Acho que o problema é com o código do objeto, pois a pesquisa pelos três outros parâmetros funciona perfeitamente. Vocês poderiam verificar?
