### ISSUE TITLE
JBWEB000065: HTTP Status 404 - /appCivicoRS/swagger/index.html

### ISSUE THREAD

**Issue by geraugu** [AppCivicoPlataforma/AppCivico#18]
Não estou conseguindo acessar no swagger api, está dando esse erro:
http://mobile-aceite.tcu.gov.br/appCivicoRS/swagger/index.html?url=/appCivicoRS/v2/api-docs

JBWEB000065: HTTP Status 404 - /appCivicoRS/swagger/index.html

JBWEB000309: type JBWEB000067: Status report

JBWEB000068: message /appCivicoRS/swagger/index.html

JBWEB000069: description JBWEB000124: The requested resource is not available.

**Comment by matbrandao** [comment]
Aparentemente toda a plataforma está offline...

**Comment by allantorres** [comment]
Também não consigo acessar nada... 
Creio que esteja fora do ar.

**Comment by monilouise** [comment]
Prezados,

O serviço já está no ar novamente.

Att.
Equipe do projeto.
