### ISSUE TITLE
Pesquisa por especialidades

### ISSUE THREAD

**Issue by D1Alexandre** [AppCivicoPlataforma/AppCivico#19]
A pesquisa de especialidades não esta funcionado , sempre retorna [ ]

segue link , para teste : http://mobile-aceite.tcu.gov.br/mapa-da-saude//rest/especialidades/unidade/2408107408765

**Comment by nmschumacher** [comment]
Prezado @d1hacker,

Nem todos os estabelecimentos possuem especialidades registradas. Por exemplo, as consultas com estes códigos não retornam uma lista vazia: 2704302006499, 3303300012505, 4314902237660.

http://mobile-aceite.tcu.gov.br/mapa-da-saude/rest/especialidades/unidade/3303300012505

Sugiro que, para encontrar estabelecimentos que possuem determinada especialidade, utilize o serviço `/rest/estabelecimentos` com o filtro por especialidade. Segue o exemplo da busca de estabelecimentos do estado de São Paulo que possuem especialidade em pneumologia:

http://mobile-aceite.tcu.gov.br/mapa-da-saude/rest/estabelecimentos?especialidade=PNEUMOLOGIA&uf=sp

Também é possível utilizar a plataforma [Swagger](http://mobile-aceite.tcu.gov.br/mapa-da-saude/swagger/index.html?url=/mapa-da-saude/v2/api-docs#!/estabelecimentos/recuperarEstabelecimentosUsingGET) para facilitar as consultas.

Att.
Equipe do projeto.
