### ISSUE TITLE
Adicionar outros parâmetros de pesquisa

### ISSUE THREAD

**Issue by cptullio** [AppCivicoPlataforma/AppCivico#20]
Seria possível adicionar outros filtros na. Api de resgate de escolas?  Por exemplo...  Gostaria de consultar por esfera administrativa,. As escolas que possuem laboratório de informática etc...

Não visualizei estas possibilidades no serviço.

Não gostaria de resgatar todas as escolas da base de vocês para fazer tal filtro...

**Comment by cptullio** [comment]
Fica uma dica para definir um parâmetro similar a campos (que retorna os campos da seleção) ter um campo filtros onde recebe campo1_valor;campo2_valor...

**Comment by SkiaBr23** [comment]
@cptullio,

Atualmente, a estrutura dos serviços de busca por escolas e outros seguem um modelo de busca via parâmetros opcionais. Existem sim alguns atributos que ainda não possuem disponibilidade para serem inseridos na busca e estamos implementando de acordo com a demanda.

Vamos analisar sua sugestão de busca em _batch_ dos atributos e então mando um feedback por aqui.

**Comment by luciocamilo** [comment]
Também sinto a necessidade de utilizar mais do que os parâmetros de filtro que são disponibilizados. Uma sugestão seria ter a possibilidade de filtrar por quaisquer dos campos disponíveis, caso contrário teria que recuperar toda a informação e depois fazer uma busca iterativa buscando o filtro que eu desejo.

**Comment by AppCivicoPlataforma** [comment]
@cptullio e @luciocamilo ,

Não será implementado mecanismo de filtro com parâmetros não conhecidos _a priori,_ a exemplo do que fazem outras APIs conhecidas (e.g. [GitHub ](https://developer.github.com/v3/)e [PayPal](https://developer.paypal.com/docs/api/)).  

Sugerimos que vocês **implementem os filtros na própria aplicação** ou abram novas _issues_ demandando filtros _específicos_ a serem usados em suas aplicações. 

Atenciosamente,

Equipe do [Desafio de Aplicativos Cívicos](http://portal.tcu.gov.br/desafio-aplicativos-civicos/o-desafio/).
