### ISSUE TITLE
WebServices para armazenar/recuperar dados para controle social e ao controle externo

### ISSUE THREAD

**Issue by Eversonbadaro** [AppCivicoPlataforma/AppCivico#21]
Olá.  No link principal do desafio (http://portal.tcu.gov.br/desafio-aplicativos-civicos/como-participar/)  está escrita a possibilidade de que alguns tópicos transversais poderiam vir a atender a todos os temas citados, e que interessariam particularmente ao controle social e ao controle externo. 

Um dos itens é o de "Gerar informações relativas à frequência de uso, qualidade do atendimento e condições de infraestrutura, acessibilidade e disponibilidade de instalações e serviços públicos."

Para conseguirmos essas informações seria necessário armazenarmos alguns dados.

Pergunto:  há  alguma possibilidade de, em conjunto com o TCU, idealizarmos uma estrutura de armazenamento de dados no ambiente do TCU ? De forma a podemos armazenar e recuperar essas informações via WebServices ?  

Procurei, mas não encontrei nada similar na documentação.

Grato e no aguardo,
Everson

**Comment by Eversonbadaro** [comment]
Ops, achei o MetaModelo,  vou tentar fazer uso. 

Everson.

**Comment by SkiaBr23** [comment]
@Eversonbadaro,

Exato =D
Dê uma olhada na documentação do MetaModelo, que dá suporte a esse tipo de armazenamento de dados em forma de **postagens**.
