### ISSUE TITLE
samu 192 NATAL

### ISSUE THREAD

**Issue by D1Alexandre** [AppCivicoPlataforma/AppCivico#22]
Não é um problema tão grande mais a SAMU natal esta aparecendo I92 em vez de 192, em outras cidades estão aparecendo com o nome normal;

**Comment by AppCivicoPlataforma** [comment]
@d1hacker ,

As informações do [Cadastro Nacional de Estabelecimentos de Saúde](http://cnes.datasus.gov.br/) (CNES) são providos pelo [DataSus](http://datasus.saude.gov.br/). Nossa equipe expõe os dados desta base [por meio de Web Services](http://mobile-aceite.tcu.gov.br/appCivicoRS/swagger/index.html?url=/mapa-da-saude/v2/api-docs), mas não temos gestão sobre a atualização dos dados.

Sugiro, pois, informar ao [próprio Datasus](http://datasus.saude.gov.br/sistemas-e-aplicativos/suporte-tecnico/capacitacao-service-desk) acerca do ruído na base de dados.

Atenciosamente,

Equipe do [Desafio de Aplicativos Cívicos](http://portal.tcu.gov.br/desafio-aplicativos-civicos/o-desafio/).
