### ISSUE TITLE
GET /rest/grupos

### ISSUE THREAD

**Issue by thiagonunes-silva** [AppCivicoPlataforma/AppCivico#24]
Pessoal, quando eu estou fazendo a pesquisa de grupos informando o código do aplicativo, a descrição, o código do tipo de objeto e o código do objeto estou tomando um erro. Acho que o problema é com o código do objeto, pois a pesquisa pelos três outros parâmetros funciona perfeitamente. Vocês poderiam verificar?

Seria possível disponibilizar uma pesquisa que pudesse retornar a lista de grupos de uma pessoa?

**Comment by SkiaBr23** [comment]
@thiagonunes-silva,

Obrigado por reportar esse erro! Já corrigimos o problema e iremos publicar as alterações, juntamente com um novo parâmetro de "**codPessoa**" na busca genérica de grupos, permitindo o retorno dos grupos em que esta pessoa é membro. Avisaremos quando for publicado.

Atenciosamente,

Equipe do [Desafio de Aplicativos Cívicos](http://portal.tcu.gov.br/desafio-aplicativos-civicos/o-desafio/).

**Comment by nmschumacher** [comment]
Caro @thiagonunes-silva,

A pesquisa que retorna os grupos de um determinado usuário já está disponível via `GET - rest/grupos`. Basta utilizar o filtro **codPessoa**.

A busca pelo código do objeto realmente tinha um erro e foi corrigido.

Obrigado pelo feedback!
