### ISSUE TITLE
Problema com o  'telefone'  no EndPoint de Estabelecimentos de Saude

### ISSUE THREAD

**Issue by Eversonbadaro** [AppCivicoPlataforma/AppCivico#25]
Olá.  No uso do endpoint de Estabelecimentos de Saude Georeferenciado  coloquei o campo 'telefone' na listagem dos campos. Tudo vinha bem, mas para o Estabelecimento "CLINICA OLIMPO" o campo Telefone não foi retornado, gerando um erro que estou contornando via código.

Pergunto: 

1) O campo telefone não está descrito entre os "Dados disponíveis", mas está retornando quando não se especifica os campos desejados.  Devo assumir que este campo nem sempre virá ou houve algum erro ?

2) Alguns campos, mesmo estando disponíveis na listagem de "Dados disponíveis",, poderão não vir nas respostas do endpoint ?   Quando o campo não estiver preenchido no cadastro, por exemplo...  ou o MetaDado virá, mas com conteúdo em branco ? 

Grato e no aguardo,
Everson

**Comment by SkiaBr23** [comment]
@Eversonbadaro,

Qual seria a fonte desses "**Dados disponíveis**" que você mencionou?

**Comment by Eversonbadaro** [comment]
Segue o link onde estão dos "Dados Disponíveis"   https://github.com/AppCivicoPlataforma/AppCivico/blob/master/EstabelecimentosAPI.md

**Comment by SkiaBr23** [comment]
@Eversonbadaro,

Obrigado por reportar esse problema! Realmente não constava nos [Dados disponíveis](https://github.com/AppCivicoPlataforma/AppCivico/blob/master/EstabelecimentosAPI.md#dados-disponíveis) os atributos **'telefone'** e também **'cnpj**'. Já [corrigi a documentação](https://github.com/AppCivicoPlataforma/AppCivico/commit/0a0126f8732e6bacac8a2cd1a96841979f1b2649).

Sobre esse e outros estabelecimentos não retornarem o campo 'telefone', isso se deve ao fato de que não temos essa informação cadastrada na base de dados. Sugiro verificar os dados recebidos no aplicativo e talvez indicar como '_Não cadastrado_' caso a informação esteja faltando.

As informações do [Cadastro Nacional de Estabelecimentos de Saúde](http://cnes.datasus.gov.br/) (CNES) são providos pelo [DataSus](http://datasus.saude.gov.br/). Nossa equipe expõe os dados desta base por meio de [Web Services](http://mobile-aceite.tcu.gov.br/appCivicoRS/swagger/index.html?url=/mapa-da-saude/v2/api-docs), mas não temos gestão sobre a atualização dos dados.

Sugiro, pois, informar ao [próprio Datasus](http://datasus.saude.gov.br/sistemas-e-aplicativos/suporte-tecnico/capacitacao-service-desk) acerca do ruído na base de dados.

Atenciosamente,

Equipe do [Desafio de Aplicativos Cívicos](http://portal.tcu.gov.br/desafio-aplicativos-civicos/o-desafio/).
