### ISSUE TITLE
Filtro para esferaAdministrativa

### ISSUE THREAD

**Issue by luciocamilo** [AppCivicoPlataforma/AppCivico#26]
Sugiro a criação de um filtro para esferaAdministrativa.

**Comment by nmschumacher** [comment]
@luciocamilo,

O filtro por esferaAdministrativa já está disponível no serviço que recupera as escolas: `GET - rest/escolas`.

Att.
Equipe do [Desafio de Aplicativos Cívicos](http://portal.tcu.gov.br/desafio-aplicativos-civicos/o-desafio/).
