### ISSUE TITLE
Uso dos webservices do metamodelo

### ISSUE THREAD

**Issue by monilouise** [AppCivicoPlataforma/AppCivico#27]
Prezados @luciocamilo, @Eversonbadaro, @thiagonunes-silva, @luarfaria, @d1hacker, @cptullio, @geraugu, @matbrandao, @allantorres, @eduardobreno, @LoveraSantiago, @jrpacheco, @ragulhari, @andre991, @caduvieira, @jardelnovaes, @joaopaulopereira, @alvarowolfx,

Dada a sua atividade na plataforma GitHub, identificamos que você está participando do _Desafio de Aplicativos Cívicos_.

De acordo com o item 6.2.5 do edital:

"O aplicativo deve ser baseado na plataforma de serviços de dados do TCU e utilizar pelo menos os webservices do metamodelo para hospedagem de dados gerados pelos usuários (ver Anexo I para detalhes)."

Dessa forma, o aplicativo deve incluir, por exemplo, funcionalidades para envio de postagens pelos usuários do aplicativo e criação de grupos.  Outros recursos, tais como uso de _hashtags_ e upload de postagens com conteúdo binário também estão disponíveis na API fornecida.  Para mais informações sobre os recursos da API, consulte os links abaixo:
- [https://github.com/AppCivicoPlataforma/AppCivico#metamodelo](https://github.com/AppCivicoPlataforma/AppCivico#metamodelo)  
- [http://mobile-aceite.tcu.gov.br/appCivicoRS/rest/api-doc](http://mobile-aceite.tcu.gov.br/appCivicoRS/rest/api-doc) 

Se você enfrentou alguma dificuldade para usar o metamodelo ou tem alguma dúvida de como utilizar o serviço, entre em contato pelo e-mail appcivico@tcu.gov.br. 

Atenciosamente,
Equipe do [Desafio de Aplicativos Cívicos](http://portal.tcu.gov.br/desafio-aplicativos-civicos/o-desafio/).

**Comment by matbrandao** [comment]
@monilouise Òbrigado pelo aviso. Mas fiquei com uma dúvida. Você quis dizer que a criação de grupos, e o envio de postagens pelo usuário é estritamente obrigatório?

Obrigado

**Comment by monilouise** [comment]
@matbrandao 

A criação de grupos e envio de postagens são exemplos.  Deve-se atentar para a exigência de que os webservices do metamodelo sejam utilizados para hospedagem de dados gerados por usuários.

Atenciosamente,
Equipe do Desafio de Aplicativos Cívicos.

**Comment by luarfaria** [comment]
Olá @monilouise, enfrento algumas dificuldades para hospedar os dados do meu app exclusivamente no metamodelo,, uma vez que as operações de objetos genéricos (POSTAGEM), por exemplo a consulta, atende apenas os critérios de GET por código e por usuário. Haveria problema se meu app enviasse os dados para a nuvem mas também tivesse um outro repositório para consultar os dados de maneira mais eficiente?

Abs,

Luar

**Comment by allantorres** [comment]
E ai pessoal , tudo bem? Será que rolava um hangout sobre esse assunto, to precisando de um help sobre esse metamodelo também, tem algumas abstrações de dados ali que eu não capitei a ideia do que se trata.

**Comment by D1Alexandre** [comment]
Seria legal mesmo , também nao entendi muito bem o uso desse metamodelo, vamos marcar....

**Comment by cptullio** [comment]
Pessoal..  Basta seguir o modelo de dados...

Enviado do meu iPhone

**Comment by luciocamilo** [comment]
Perguntei sobre as logomarcas e não obtive resposta, alguém sabe de algo?

2016-09-24 15:00 GMT-03:00 cptullio notifications@github.com:

**Comment by AppCivicoPlataforma** [comment]
@luciocamilo,

Sua mensagem foi recebida na caixa institucional. Ocorre que as logamarcas ainda não foram disponibilizadas. Como outros colegas também perguntaram, quando forem disponibilizadas (e esta atividade foi priorizada internamente), avisaremos por meio de uma issue e também por e-mail.

Ademais, peço-lhe que inicie nova thread quando o assunto não for associado à issue em tela.

Atenciosamente,

Equipe do [Desafio de Aplicativos Cívicos](http://portal.tcu.gov.br/desafio-aplicativos-civicos/o-desafio/).

**Comment by luarfaria** [comment]
Olá @monilouise @AppCivicoPlataforma, enfrento algumas dificuldades para hospedar os dados do meu app exclusivamente no metamodelo,, uma vez que as operações de objetos genéricos (POSTAGEM), por exemplo a consulta, atende apenas os critérios de GET por código e por usuário. Haveria problema se meu app enviasse os dados para a nuvem mas também tivesse um outro repositório para consultar os dados de maneira mais eficiente?

Abs,

Luar

**Comment by monilouise** [comment]
Prezado @luarfaria ,

A busca por postagens possui várias opções de filtros: http://mobile-aceite.tcu.gov.br/appCivicoRS/swagger/index.html?url=/appCivicoRS/v2/api-docs#!/postagens/recuperarPostagensUsingGET_1 

Se sua aplicação tem necessidade de alguma outra consulta que não esteja disponível, podemos adicionar mais critérios de busca.

Com relação a hospedar os dados em outro repositório, não há problema, desde que haja hospedagem de dados também no metamodelo providos pelo TCU.

Atenciosamente,
Equipe do [Desafio de Aplicativos Cívicos](http://portal.tcu.gov.br/desafio-aplicativos-civicos/o-desafio/).

**Comment by monilouise** [comment]
Prezados @allantorres e @d1hacker ,

Quais são as dúvidas específicas com relação ao uso do metamodelo?

Atenciosamente,
Equipe do [Desafio de Aplicativos Cívicos.](http://portal.tcu.gov.br/desafio-aplicativos-civicos/o-desafio/)

**Comment by allantorres** [comment]
@monilouise 
Já foi resolvido o problema no meu caso. Obrigado pela atenção.

**Comment by LoveraSantiago** [comment]
Os recursos de metamodelo, os endpoints restful, continuarão ativos após o concurso, ou serão encerrados em uma determinada data?

Alguma resposta?

**Comment by AppCivicoPlataforma** [comment]
@LoveraSantiago,

Tanto os recursos do metamodelo quando os webservices que expõem dados abertos permanecerão ativos após o concurso.

Estamos planejando [evoluções na API](https://github.com/AppCivicoPlataforma/AppCivico/projects/1), mas devemos implementá-las apenas ao final do Desafio. De todo modo, os desenvolvedores serão notificados por meio desta plataforma.

Atenciosamente,

Equipe do [Desafio de Aplicativos Cívicos](http://portal.tcu.gov.br/desafio-aplicativos-civicos/o-desafio/).
