### ISSUE TITLE
Permissão de acesso aos headers de response

### ISSUE THREAD

**Issue by eduardobreno** [AppCivicoPlataforma/AppCivico#29]
Olá, 
ao realizar o login não consigo acessar o `appToken` no header de resposta. Pesquisando, vi que é preciso adicionar no servidor a opção `Access-Control-Expose-Headers` com os headers que podem ser acessados. Isso ajudaria o desenvolvimento em testes nos navegadores.

**Comment by AppCivicoPlataforma** [comment]
@eduardobreno,

Outros colegas que participam do [Desafio de Aplicativos Cívicos](http://portal.tcu.gov.br/desafio-aplicativos-civicos/o-desafio/) não reportaram problema semelhante para acessar os _headers_ de resposta.

Destarte, é mister que nos forneça informações específicas de tua infraestrutura para que tenhamos condições de ajudar:
- Que _frameworks_/tecnologias você está utilizando para construir seu aplicativo?
- Que erro você recebe ao tentar acessar o **appToken**?

Atenciosamente,

Equipe do [Desafio de Aplicativos Cívicos](http://portal.tcu.gov.br/desafio-aplicativos-civicos/o-desafio/).

**Comment by eduardobreno** [comment]
@AppCivicoPlataforma ,

Utilizo o ionic como framework, os testes durante o desenvolvimento acontecem mais nos navegadores do desktop e quando vou testar nos devices é utilizado o modo --livereload onde me permite reescrever códigos sem precisar fazer build da aplicação a todo momento.

Já havia solicitado outras mudanças nesse sentido devido a usar esse framework no issue #15  .

O que acontece é que o angular não consegue enxergar o header de retorno, apenas o header Content-Type é acessado, os demais ele não consegue acessar. Esse problema não acontece quando eu faço build completo sem as facilidades que o Framework proporciona. 

Essa solicitação é apenas para o desenvolvimento do app, não será necessário depois que estiver na loja.

Se não for possível agradeço a atenção.

**Comment by allantorres** [comment]
Alguém conseguiu usar o appToken no phonegap? 
Cadastrar usuário?

**Comment by eduardobreno** [comment]
@allantorres,
Consigo acessar apenas quando faço o build para gerar o app, quando executo nos navegadores não consigo acessar.

**Comment by allantorres** [comment]
@eduardobreno será que podemos conversar pois eu consegui fazer alguns GETs e consigo já ver as infromações tranaquilamente, no app , só não consigo fazer os PUTs como criar um usuário.

**Comment by SkiaBr23** [comment]
@eduardobreno  e @allantorres,

Acabei de inserir a opção '_Access-Control-Expose-Headers_' ao filtro de headers do metamodelo. 

Poderiam testar novamente e mandar um feedback?

**Comment by allantorres** [comment]
@SkiaBr23 
Consegui fazer o POST e GET sem maiores problemas...  creio que poderia ser essa opção que estava realmente faltando. Mas de qualquer forma obrigado.  👍

**Comment by eduardobreno** [comment]
@SkiaBr23, 
Aqui também!

**Comment by AppCivicoPlataforma** [comment]
@eduardobreno  e @allantorres,

A opção '_Access-Control-Expose-Headers_'  será removida dia 21/10/2016, data final para envio das propostas para o [Desafio de Aplicativos Cívicos](http://portal.tcu.gov.br/desafio-aplicativos-civicos/o-desafio/), conforme [descrito em edital](http://portal.tcu.gov.br/lumis/portal/file/fileDownload.jsp?fileId=8A8182A2561DF3F5015695395F263C64).

Atenciosamente,
Equipe do [Desafio de Aplicativos Cívicos](http://portal.tcu.gov.br/desafio-aplicativos-civicos/o-desafio/).
