### ISSUE TITLE
Endpoint de escolas retornando escolas fora do raio

### ISSUE THREAD

**Issue by LucianoPAlmeida** [AppCivicoPlataforma/AppCivico#3]
O end point de escolas está retornando escolas erradas na busca por coordenadas.
Começou recentemente e está retornando as escolas de maneira incorreta. Como no exemplo:
![img_1392](https://cloud.githubusercontent.com/assets/8292651/16327834/0c36b29e-39aa-11e6-926a-90f9adafd329.jpg)

Onde o ponto azul é a localização do usuário(parâmetro da busca) e o ponto com 115 são as escolas retornadas agrupadas. A url é a seguinte: 
http://mobile-aceite.tcu.gov.br/nossaEscolaRS/rest/escolas?latitude=-15.9353&longitude=-48.092&raio=10

Fiz um teste no browser com a mesma url:

<img width="1280" alt="screen shot 2016-06-24 at 01 13 02" src="https://cloud.githubusercontent.com/assets/8292651/16327845/36095162-39aa-11e6-814f-eae25b9afd2e.png">

A parte que está selecionada são as coordenadas da primeira escola selecionada, a qual peguei para teste, confirmando que a busca está retornado as escolas erradas. Como mostra a imagem onde eu coloco a coordenada selecionada ("latitude":-8.7659235,"longitude":-63.86447) em um site de mapas.

<img width="1280" alt="screen shot 2016-06-24 at 01 16 39" src="https://cloud.githubusercontent.com/assets/8292651/16327851/4d8cf49c-39aa-11e6-93a0-1aa3e7b0a273.png">

Confirmando que o problema está na resposta do endpoint.

**Comment by marcelopacote** [comment]
This issue is already solved.
