### ISSUE TITLE
Algumas escolas não possuem todos os dados descritos nos campos

### ISSUE THREAD

**Issue by luciocamilo** [AppCivicoPlataforma/AppCivico#30]
Um dos campos contidos no body de "infraestrutura" por exemplo é esse:
    "atendeEducacaoEspecializada": "string"
Ocorre que quando se faz uma requisição por exemplo na escola de id 33094152, esse mesmo campo não é retornado.

**Comment by SkiaBr23** [comment]
@luciocamilo,

Algumas escolas na base de dados não possuem alguns atributos cadastrados, apenas retornando os campos em que há informação registrada. 

[Nesse exemplo](http://mobile-aceite.tcu.gov.br/nossaEscolaRS/rest/escolas/53015240), o atributo _atendeEducacaoEspecializada_ é retornado.

As informações do Censo Escolar são providas pelo [Instituto Nacional de Estudos e Pesquisas Educacionais Anísio Teixeira (INEP)](http://portal.inep.gov.br/). Nossa equipe expõe os dados desta base por meio de Web Services, mas não temos gestão sobre a atualização dos dados.

Sugiro, pois, informar ao próprio INEP acerca do ruído na base de dados.

Atenciosamente,

Equipe do [Desafio de Aplicativos Cívicos](http://portal.tcu.gov.br/desafio-aplicativos-civicos/o-desafio/).
