### ISSUE TITLE
Dados inconsistentes

### ISSUE THREAD

**Issue by LoveraSantiago** [AppCivicoPlataforma/AppCivico#31]
Boa noite. 

1 - Realizando a seguinte busca:

[http://mobile-aceite.tcu.gov.br:80/mapa-da-saude/rest/estabelecimentos/latitude/-23.445088/longitude/-46.7495928/raio/5?categoria=farmacia&quantidade=200](url)

Os dados dessa unidade 3550306300081 estão com geolocalização errados. É bastante distante de onde moro e na consulta que realizo com um raio de 5 km ele retorna esse estabelecimento. De acordo com o maps 

[https://www.google.com.br/maps/place/R.+Gen.+Roberto+Alves+de+Carvalho+Filho,+270+-+Santo+Amaro,+S%C3%A3o+Paulo+-+SP/@-23.6557533,-46.7079821,17z/data=!3m1!4b1!4m5!3m4!1s0x94ce5053b7431f11:0xde86df4b8fafb8bb!8m2!3d-23.6557533!4d-46.7057881?hl=pt-BR
](url)

a geolocalização é diferente.

2 - A base de dados de farmácia, seriam as farmacias populares ou qualquer especie de farmácia?

**Comment by luciocamilo** [comment]
Reparei que muitas escolas não possuem esses dados de long e lat. Acredito que deva ser normal essa inconsistência..

**Comment by SkiaBr23** [comment]
@LoveraSantiago,

As informações do [Cadastro Nacional de Estabelecimentos de Saúde (CNES)](http://cnes.datasus.gov.br/) são providos pelo [DataSus](http://datasus.saude.gov.br/). Nossa equipe expõe os dados desta base por meio de Web Services, mas não temos gestão sobre a atualização dos dados.

Sugiro, pois, informar ao [próprio Datasus](http://datasus.saude.gov.br/sistemas-e-aplicativos/suporte-tecnico/capacitacao-service-desk) acerca do ruído na base de dados.

Atenciosamente,

Equipe do [Desafio de Aplicativos Cívicos](http://portal.tcu.gov.br/desafio-aplicativos-civicos/o-desafio/).
