### ISSUE TITLE
Longitude e palavra reservada

### ISSUE THREAD

**Issue by LoveraSantiago** [AppCivicoPlataforma/AppCivico#32]
Bom dia. 

Dentro de estabelecimentos temos a localização através de latitude e longitude. No modelo esta sendo usada a palavra "long". Penso não ser muito apropriado esse "diminutivo" visto que em linguagens sólidas e de peso como Java e C++,  long é uma palavra reservada. 

Para os desenvolvedores Android, que usam Java, onde long é uma palavra reservada complica um pouco a vida. 

Por exemplo usar libs que consomem o Rest e já parseiam o json em um objeto java a informação de longitude fica perdida. 

Mesmo para o parseamento feito "manualmente" ha perca de performance.

Qual a possibilidade de alterar o nome desse campo?

**Comment by AppCivicoPlataforma** [comment]
@LoveraSantiago,

De fato, o uso de _long_ em vez _longitude_ não foi escolha apropriada. Desafortunadamente, há muitos _hackers_ desenvolvendo aplicações que fazem uso deste termo e não há previsão para atualização do nome.

De todo modo, agradecemos a sugestão. Ficaremos atentos para que situações semelhantes não ocorram quando da modelagem de novos campos.

Atenciosamente,

Equipe do [Desafio de Aplicativos Cívicos](http://portal.tcu.gov.br/desafio-aplicativos-civicos/o-desafio/).
