### ISSUE TITLE
Mais de um aplicativo

### ISSUE THREAD

**Issue by allantorres** [AppCivicoPlataforma/AppCivico#33]
Pessoal, não ficou claro pra mim se podemos participar com mais de um aplicativo. 

Alguém sabe me responder essa questão?

**Comment by matbrandao** [comment]
Pelo edital eu vi que para cada inscrito, é possível entrar com 2 aplicativos.

**Comment by SkiaBr23** [comment]
@allantorres,

De acordo com o item 4.2 do edital:

**"Cada proponente poderá submeter até duas propostas."**

Atenciosamente,

Equipe do [Desafio de Aplicativos Cívicos](http://portal.tcu.gov.br/desafio-aplicativos-civicos/o-desafio/).
