### ISSUE TITLE
Dado consta no modelo mas não existe na reposta

### ISSUE THREAD

**Issue by luciocamilo** [AppCivicoPlataforma/AppCivico#34]
tipoConvenioPoderPublico é citado no model schema no entanto não existe nas respostas.

**Comment by SkiaBr23** [comment]
@luciocamilo,

Obrigado por reportar o erro! Verificamos que esse campo e o de _telefone_ realmente não estão sendo retornados nas buscas. 

Estamos averiguando a causa desse problema e logo que for resolvido avisarei por aqui.

Atenciosamente,

Equipe do [Desafio de Aplicativos Cívicos](http://portal.tcu.gov.br/desafio-aplicativos-civicos/o-desafio/).

**Comment by SkiaBr23** [comment]
@luciocamilo,

A falha no retorno desses dados de _telefone_ e _tipoConvenioPublico_ ocorreu pelo fato desses atributos não estarem disponíveis atualmente na base de dados. Solicitamos a atualização da base e a mesma será feita em breve.

Aviso por aqui quando os dados estiverem disponíveis.

Atenciosamente,

Equipe do [Desafio de Aplicativos Cívicos](http://portal.tcu.gov.br/desafio-aplicativos-civicos/o-desafio/).

**Comment by marcelopacote** [comment]
@luciocamilo.

A base de dados foi atualizada. Por obséquio, verifique se os dados de _tipoConvenioPoderPublico_ estão sendo retornados nas consultas. 

Atenciosamente,

Equipe do [Desafio de Aplicativos Cívicos](http://portal.tcu.gov.br/desafio-aplicativos-civicos/o-desafio/).
