### ISSUE TITLE
Dúvida metamodelo Postagem

### ISSUE THREAD

**Issue by eduardobreno** [AppCivicoPlataforma/AppCivico#35]
Analisando o metamodelo, vi que é possível realizar posts, mas não vi função de comentário.
Existe alguma forma de utilizar as funções já existentes como forma de comentários? (caso não, podem implementar?)

**Comment by SkiaBr23** [comment]
@eduardobreno,

O metamodelo disponibiliza a entidade de _"Postagem"_ e _"TipoPostagem"_, assim como relações de _postagem-pai_ e _postagem relacionada_ para que seja feita a modelagem de **qualquer tipo** de armazenamento de dados necessária para **qualquer app**.

Exemplo: Um comentário pode ser modelado como uma postagem do tipo "Comentário", possivelmente com o atributo "_postagemPai_" setado com o código da postagem que o usuário enviou o comentário. Curtidas, avaliações e etc também podem ser modeladas como postagens de diferentes tipos/conteúdos/relações.

É pra isso que serve o metamodelo, disponibilizar uma interface mais genérica que pode ser **moldada** de qualquer forma pelo desenvolvedor.

Atenciosamente,

Equipe do [Desafio de Aplicativos Cívicos](http://portal.tcu.gov.br/desafio-aplicativos-civicos/o-desafio/).
