### ISSUE TITLE
Poucas escolas retornam quando faço a consulta na cidade de São Paulo

### ISSUE THREAD

**Issue by nilsonivano** [AppCivicoPlataforma/AppCivico#36]
Consultando o rest utilizando a base:
http://mobile-aceite.tcu.gov.br/nossaEscolaRS/rest/escolas/latitude/-23.556967/longitude/-46.638451/raio/100000

A consulta retorna somente 20 escolas. Esse valor está correto mesmo ou há alguma restrição de retorno?

Obrigado

**Comment by AppCivicoPlataforma** [comment]
@nilsonivano,

Conforme especifica a [documentação da API](http://mobile-aceite.tcu.gov.br/nossaEscolaRS/swagger/index.html?url=/nossaEscolaRS/v2/api-docs#!/escolas/recuperarEscolasUsingGET), deve-ser utilizar o parâmetro **quantidadeDeItens** para especificar a quantidade máxima de itens recuperados por pesquisa. O valor padrão do item é 20. 

Ademais, fique atento à consulta haja vista que o raio é informado em kilômetros. Eis como deveria ser montada tua chamada GET com raio de 100Km e com 200 itens sendo retornados.

`http://mobile-aceite.tcu.gov.br/nossaEscolaRS/rest/escolas/latitude/-23.556967/longitude/-46.638451/raio/100?quantidadeDeItens=200`

Atenciosamente,

Equipe do [Desafio de Aplicativos Cívicos](http://portal.tcu.gov.br/desafio-aplicativos-civicos/o-desafio/).
