### ISSUE TITLE
Consulta de estabelecimento retorna um array

### ISSUE THREAD

**Issue by LoveraSantiago** [AppCivicoPlataforma/AppCivico#37]
Meus caros, boa noite.

A busca por estabelecimento está retornando um array de uma posição. Está correto assim mesmo ou deveria retornar o json objeto unico do estabelecimento?

Segue consulta
http://mobile-aceite.tcu.gov.br:80/mapa-da-saude/rest/estabelecimentos/unidade/3550302091801

**Comment by SkiaBr23** [comment]
@LoveraSantiago,

Obrigado por reportar o erro!

Atualmente, todas as buscas de estabelecimentos por unidade retornam apenas um resultado, o que realmente não condiz com o tipo de retorno em array. Porém, as bases de dados de saúde (estabelecimentos, postos de assistência social e emprego) têm como identificador um código diferente do código de unidade. Assim, por mais que não exista repetições no momento, nada impede que a base seja atualizada pelo CNES e passe a ter duplicatas de código de unidade.

Além disso, por estarmos numa etapa já avançada no cronograma do edital, fazer esse tipo de alteração na estrutura do código poderia comprometer o desenvolvimento de outras equipes que já estão usando o retorno como array, mesmo que de apenas uma posição. Então, essa alteração não será feita no momento.

Futuramente, iremos juntar um apanhado de _known issues_ como essa e outras sugestões pra possivelmente criar uma versão atualizada do metamodelo após o encerramento do Desafio. Essas informações estarão documentadas nesse repositório.

Atenciosamente,

Equipe do [Desafio de Aplicativos Cívicos](http://portal.tcu.gov.br/desafio-aplicativos-civicos/o-desafio/).
