### ISSUE TITLE
Coordenadas de geolocalizaçao não precisas

### ISSUE THREAD

**Issue by LoveraSantiago** [AppCivicoPlataforma/AppCivico#38]
Bom dia. 

Sei que não é responsabilidade do TCU, mas so para avisar aos colegas....

Ao integrar com maps, percebi em todos os exemplos de estabelecimento que peguei as coordenadas de geolocalização estão proximos, porem imprecisas.

Ex:
[http://mobile-aceite.tcu.gov.br:80/mapa-da-saude/rest/estabelecimentos/unidade/3505703272591](url)
retorna "lat": -23.51038, "long": -46.87501

sendo que o estabelecimento em questão é o Hospitalis

[https://www.google.com.br/maps/dir/Hospitalis+N%C3%BAcleo+Hospitalar+Barueri+-+Vila+Sao+Luiz+(Centro),+Barueri+-+SP/-23.51038,-46.87501/@-23.503436,-46.8834583,15z/data=!3m1!4b1!4m8!4m7!1m5!1m1!1s0x94cf03c6b599fe11:0x37c69fd322e294e!2m2!1d-46.878483!2d-23.502808!1m0?hl=pt-BR](url)

**Comment by matbrandao** [comment]
E ai Lovera.
Também percebi várias incoerências na base de dados. Mas imagino que essa precisão não será levada em conta no momento da avaliação dos apps. Até por que a proposta é realmente utilizar o banco de dados disponível. Corrijam me se estiver errado.

**Comment by SkiaBr23** [comment]
@LoveraSantiago,

Como dito anteriormente, a inconsistência dos dados disponíveis se deve à fatores externos. Tais ruídos na base não irão acarretar em penalidades na avaliação do aplicativo como mencionado pelo @matbrandao , ficando a critério do desenvolvedor expor os dados da maneira que a base informa ou criar _workarounds_ para resolver/ocultar o problema na aplicação.

Passo novamente essa informação pra outros usuários que ainda não viram:

As informações do [Cadastro Nacional de Estabelecimentos de Saúde (CNES)](http://cnes.datasus.gov.br/) são providos pelo [DataSus](http://datasus.saude.gov.br/). Nossa equipe expõe os dados desta base por meio de Web Services, mas não temos gestão sobre a atualização dos dados.

Sugiro, pois, informar ao [próprio Datasus](http://datasus.saude.gov.br/sistemas-e-aplicativos/suporte-tecnico/capacitacao-service-desk) acerca do ruído na base de dados.

Atenciosamente,

Equipe do [Desafio de Aplicativos Cívicos](http://portal.tcu.gov.br/desafio-aplicativos-civicos/o-desafio/).
