### ISSUE TITLE
Erro na criação de Postagem

### ISSUE THREAD

**Issue by matbrandao** [AppCivicoPlataforma/AppCivico#39]
Ao tentar criar uma postagem que possui  o parâmetro "codTipoPostagem" com valor 200 (Remédios cadastrados na ANVISA) :

{"autor":{"codPessoa":1040},"codObjetoDestino":123,"tipo":{"codTipoPostagem":200}}

Eu recebo o seguinte erro:

{
  "url": "/appCivicoRS/rest/postagens",
  "statusCode": 404,
  "reasonPhrase": "Not Found",
  "mensagens": [
    {
      "texto": "Tipo de postagem não cadastrado"
    }
  ]
}

Mas 200 é o valor que o sistema retorna como código do objeto Remédios cadastrados na ANVISA.

Ao tentar com outro codTipoPostagem, como 100 (Estabelecimentos de Saúde), eu consigo criar o post sem problemas.

**Comment by SkiaBr23** [comment]
@matbrandao,

Acredito que você esteja confundindo "**Tipo de Postagem**" com "**Tipo de Objeto**". No caso, esse código 200 para "Remédios Cadastrados na ANVISA" e o 100 para "Estabelecimentos de Saúde" são tipos de objeto. 

Sua criação de postagem resultou em erro por não existir um tipo '200' de postagem, e ao tentar com '100', você acabou usando um tipo que alguém já cadastrou. 

Sugiro **revisar a documentação** aqui do GitHub sobre tipos de objeto/tipos de postagem e testar no Swagger para ver a diferença entre eles [aqui](http://mobile-aceite.tcu.gov.br/appCivicoRS/swagger/index.html?url=/appCivicoRS/v2/api-docs#!/tipos_de_objeto) e [aqui](http://mobile-aceite.tcu.gov.br/appCivicoRS/swagger/index.html?url=/appCivicoRS/v2/api-docs#!/tipos_de_postagem).

Atenciosamente,

Equipe do [Desafio de Aplicativos Cívicos](http://portal.tcu.gov.br/desafio-aplicativos-civicos/o-desafio/).
