### ISSUE TITLE
Adcionar parametros 

### ISSUE THREAD

**Issue by geraugu** [AppCivicoPlataforma/AppCivico#4]
É possível adicionar parametros no serviço **/rest/escolas** ?

Só por município fica limitada a pesquisa. 
Sugestão, acrescentar as seguintes opções de parâmetros:
- uf
- situacaoFuncionamento
- categoriaEscolaPrivada

**Comment by LucianoPAlmeida** [comment]
Olá @geraugu 

Estamos trabalhando nessas buscas. 
Agradecemos o feedback.

**Comment by nmschumacher** [comment]
Caro @geraugu ,

Os parâmetros solicitados foram acrescentados ao serviço e estão prontos para utilização.

Obrigado pela sugestão!

**Comment by geraugu** [comment]
Desculpa, mas poderia adicionar mais 2 parâmetros de busca? 
- Rede
- Nome (ínico do nome ou parte dele)

**Comment by SkiaBr23** [comment]
@geraugu,

Os novos parâmetros de busca já foram implementados e publicados. Consulte a documentação via [Swagger](http://mobile-aceite.tcu.gov.br/appCivicoRS/swagger/index.html?url=/nossaEscolaRS/v2/api-docs#!/escolas/recuperarEscolasPorMunicipioUsingGET).

Caso outros parâmetros sejam necessários, peço que crie uma nova issue. 

Obrigado pela sugestão!

**Comment by geraugu** [comment]
Maravilha @SkiaBr23 !
Pode deixar que eu crio outra se for necessário.
Obrigado.
