### ISSUE TITLE
Documentação defasada no Metamodelo

### ISSUE THREAD

**Issue by luciocamilo** [AppCivicoPlataforma/AppCivico#40]
Estou tentando enviar uma postagem via post, no entanto a documentação está defasada. O schema mostra alguns campos que não existem na documentação, desta forma não consigo saber a que se refere o erro ao tentar enviar o seguinte json:

{
  "autor": {
    "codPessoa": 1318
  },
  "codObjetoDestino": 33032866,
  "codTipoObjetoDestino": 4
  },
  "tipo": {
    "codTipoPostagem": 119
  }
}

**Comment by nmschumacher** [comment]
@luciocamilo,

Obrigado por avisar, a documentação foi atualizada.

Repare que seu JSON contém chaves '}' a mais. Na parte

```
"codTipoObjetoDestino": 4
},
```

o JSON foi fechado nesta última chave, por isso o código do tipo de postagem não foi encontrado e este é um parâmetro obrigatório.

O seguinte código deve funcionar:

```
{
   "autor": {
      "codPessoa": 1318
   },
   "codObjetoDestino": 33032866,
   "codTipoObjetoDestino": 4,
   "tipo": {
      "codTipoPostagem": 119
   }
}
```

Att.

Equipe do [Desafio de Aplicativos Cívicos](http://portal.tcu.gov.br/desafio-aplicativos-civicos/o-desafio/).
