### ISSUE TITLE
Erro de DNS

### ISSUE THREAD

**Issue by ragulhari** [AppCivicoPlataforma/AppCivico#43]
Estou tentando utilizar o ambiente e recebo erro, aparentemente de DNS. Testei por outras redes e tenho o mesmo problema.

**Comment by eduardobreno** [comment]
Senhores, 
aqui não consigo acessar desde sexta(07/10) pela noite e ainda sem acesso no sábado.
Tanto os serviços como o sistema.

```
Mensagem:
Não é possível acessar esse site
A página da web em http://mobile-aceite.tcu.gov.br/appCivicoWeb/web/externo
```

**Comment by julianesansil** [comment]
Aqui também, não consigo desde sexta à noite.

**Comment by LoveraSantiago** [comment]
Aqui tambem. Para não ficar parado fui para a parte de layout. 
Na sexta ja imaginei que provavelmente seria restabelecido só na segunda.

**Comment by matbrandao** [comment]
@LoveraSantiago, @julianesansil, @eduardobreno , @ragulhari Acabei de testar aqui e acho que voltou.

**Comment by ragulhari** [comment]
@matbrandao realmente voltou, obrigado pelo aviso!
