### ISSUE TITLE
API fora do ar no fim de semana

### ISSUE THREAD

**Issue by luarfaria** [AppCivicoPlataforma/AppCivico#44]
Estou tentando acessar a api http://mobile-aceite.tcu.gov.br:80/nossaEscolaRS/ e esta de repente fica fora do ar várias vezes durante o fim de semana. Caso esteja sendo feita manutenção na API, sugiro que seja avisado com antecedência, visto que esse ambiente é de produção, certo?

Abs,

**Comment by marcelopacote** [comment]
@luarfaria,

Trata-se pois de manutenção programada da infraestrutura do TCU. Ela foi noticiada por meio da [página principal do portal ao cidadão](http://portal.tcu.gov.br/cidadao/cidadao.htm).

De todo modo, transcrevo abaixo o comunicado:

> Informamos que o Portal TCU e todos os demais sistemas corporativos ficarão indisponíveis das 20h de sexta-feira (7/10) às 23h de domingo (9/10) devido à manutenção programada no ambiente de TI.

Os serviços já foram todos restabelecidos. Solicito ficar atento a novos comunicados na [página principal do Tribunal](http://portal.tcu.gov.br/cidadao/cidadao.htm).

Atenciosamente,

Equipe do [Desafio de Aplicativos Cívicos](http://portal.tcu.gov.br/desafio-aplicativos-civicos/o-desafio/).

**Comment by luarfaria** [comment]
@marcelopacote acontece que a API ainda está fora, mesmo depois desse prazo.

**Comment by SkiaBr23** [comment]
@luarfaria,

A API está no ar desde o horário divulgado. Acredito que você tenha acessado por meio desse link:

> Estou tentando acessar a api http://mobile-aceite.tcu.gov.br:80/nossaEscolaRS/

Esse link é a URL base dos serviços, mas **não abre nenhuma página no navegador**. Favor utilizar a [URL do Swagger](http://mobile-aceite.tcu.gov.br/appCivicoRS/swagger/index.html?url=/nossaEscolaRS/v2/api-docs#!/) para testar o acesso à API.

Atenciosamente,

Equipe do [Desafio de Aplicativos Cívicos](http://portal.tcu.gov.br/desafio-aplicativos-civicos/o-desafio/).
