### ISSUE TITLE
POST /rest/postagens cadastrar uma nova ponstagem - schema errado

### ISSUE THREAD

**Issue by geraugu** [AppCivicoPlataforma/AppCivico#45]
Olá, 

O modelo do esquema do serviço POST /rest/postagens  diz 

> PostagemCadastrada {
> autor (Autor, optional),`

Só que ao tentar cadastrar sem autor, retorna a seguinte mensagem 

> {
>   "url": "/appCivicoRS/rest/postagensapi_key=343",
>   "statusCode": 400,
>   "reasonPhrase": "Bad Request",
>   "mensagens": [
>     {
>       "texto": "Autor não informado"
>     }
>   ]
> }

Afinal, o autor é opcional ou obrigatório?

**Comment by SkiaBr23** [comment]
@geraugu,

A informação de autor é obrigatória no cadastro de Postagem. Vou corrigir o esquema para mostrar os dados corretos. Obrigado por reportar o erro!

[UPDATE] Alterações publicadas.

Atenciosamente,

Equipe do [Desafio de Aplicativos Cívicos](http://portal.tcu.gov.br/desafio-aplicativos-civicos/o-desafio/).
