### ISSUE TITLE
Inclusão de filtro de categoria em GET - /rest/estabelecimentos

### ISSUE THREAD

**Issue by ragulhari** [AppCivicoPlataforma/AppCivico#46]
Boa tarde,

Verificando as chamadas referentes a estabelecimentos percebi que na chamada georeferenciada (GET - /rest/estabelecimentos/latitude/{latitude}/longitude/{longitude}/raio/{raio}) existe um filtro por "**categoria**". 

Porém na chamada não georeferenciada (GET - /rest/estabelecimentos) não existe esse filtro. Seria possível adicionar esse filtro de categoria nessa última chamada?

Grato, Ricardo

**Comment by SkiaBr23** [comment]
@ragulhari,

Obrigado pela sugestão! Já adicionamos o novo campo _categoria_ na busca de estabelecimentos. Você pode testar o funcionamento [via Swagger](http://mobile-aceite.tcu.gov.br/appCivicoRS/swagger/index.html?url=/mapa-da-saude/v2/api-docs#!/estabelecimentos/recuperarEstabelecimentosUsingGET).

Atenciosamente,

Equipe do [Desafio de Aplicativos Cívicos](http://portal.tcu.gov.br/desafio-aplicativos-civicos/o-desafio/).
