### ISSUE TITLE
Ordenação por proximidade - API Georeferenciada de estabelecimentos

### ISSUE THREAD

**Issue by ragulhari** [AppCivicoPlataforma/AppCivico#47]
Boa tarde,

Gostaria de verificar a possibilidade de adicionar uma ordenação por proximidade na api georeferenciada de estabelecimentos (GET - /rest/estabelecimentos/latitude/{latitude}/longitude/{longitude}/raio/{raio}). Fazendo alguns testes aqui percebi que alguns locais próximos não aparecem em um determinado local e, mudando um pouco a posição (coisa de duas ruas) esses lugares passam a aparecer. Estou usando o raio como 50Km, cheguei a fazer testes com 200 estabelecimentos e ainda percebo esse tipo de oscilação

Grato,
Ricardo

**Comment by SkiaBr23** [comment]
@ragulhari,

Atualmente, todas as buscas georreferenciadas retornam seus resultados ordenados pela distância do ponto enviado por parâmetro. Porém, como dito previamente, existem inconsistências na base de dados que podem acarretar em resultados não esperados.

Você poderia mandar exemplos de busca nos quais você observou essa oscilação para que possamos analisar a possível falha?

Atenciosamente,

Equipe do [Desafio de Aplicativos Cívicos](http://portal.tcu.gov.br/desafio-aplicativos-civicos/o-desafio/).

**Comment by SkiaBr23** [comment]
@ragulhari
Reiterando,

> Você poderia mandar exemplos de busca nos quais você observou essa oscilação para que possamos analisar a possível falha?

**Comment by ragulhari** [comment]
@SkiaBr23 tudo bem?

Peço desculpas por não ter conseguido enviar ainda, estou impossibilitado esses dias por questões de trabalho, vou fechar esse tópico e abro um novo com os exemplos assim que possível.

Grato, Ricardo
