### ISSUE TITLE
Reativacao de usuario excluido esta inoperante

### ISSUE THREAD

**Issue by Bonissauro** [AppCivicoPlataforma/AppCivico#48]
Ao tentar reativar uma Pessoa escluida com o DELETE, recebo o response abaixo:

{
  "url": "/appCivicoRS/rest/pessoas/reativar",
  "statusCode": 500,
  "reasonPhrase": "Internal Server Error",
  "siglaErro": "SEGURANCA_010857",
  "dadosTecnicos": "br.gov.tcu.arquitetura.util.excecao.ExcecaoNaoPrevista: SEGURANCA_010857\n<br/>at br.gov.tcu.arquitetura.is.ws.rest.excecao.TratadorExcecaoNegocioArqref7EThrowable.tratarExcecao(TratadorExcecaoNegocioArqref7EThrowable.java:54)\n<br/>at br.gov.tcu.arquitetura.is.ws.rest.excecao.TratadorExcecaoNegocioArqref7EThrowable$$FastClassBySpringCGLIB$$f12bd73b.invoke(<generated>)\n<br/>at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)\n<br/>at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:717)\n<br/>at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)\n<br/>at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)\n<br/>at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)\n<br/>at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)\n<br/>at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)\n<br/>at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:653)\n<br/>at br.gov.tcu.arquitetura.is.ws.rest.excecao.TratadorExcecaoNegocioArqref7EThrowable$$EnhancerBySpringCGLIB$$53574ea5.tratarExcecao(<generated>)\n<br/>at br.gov.tcu.arquitetura.is.ws.rest.excecao.RestExceptionHandler.tratarExcecaoGenerica(RestExceptionHandler.java:127)\n<br/>at sun.reflect.GeneratedMethodAccessor1396.invoke(Unknown Source)\n<br/>at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n<br/>at java.lang.reflect.Method.invoke(Method.java:606)\n<br/>at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)\n<br/>at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)\n<br/>at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)\n<br/>at org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver.doResolveHandlerMethodException(ExceptionHandlerExceptionResolver.java:362)\n<br/>at org.springframework.web.servlet.handler.AbstractHandlerMethodExceptionResolver.doResolveException(AbstractHandlerMethodExceptionResolver.java:60)\n<br/>at org.springframework.web.servlet.handler.AbstractHandlerExceptionResolver.resolveException(AbstractHandlerExceptionResolver.java:138)\n<br/>at org.springframework.web.servlet.handler.HandlerExceptionResolverComposite.resolveException(HandlerExceptionResolverComposite.java:74)\n<br/>at org.springframework.web.servlet.DispatcherServlet.processHandlerException(DispatcherServlet.java:1183)\n<br/>at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1020)\n<br/>at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:971)\n<br/>at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)\n<br/>at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:967)\n<br/>at org.springframework.web.servlet.FrameworkServlet.doPut(FrameworkServlet.java:880)\n<br/>at javax.servlet.http.HttpServlet.service(HttpServlet.java:757)\n<br/>at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:843)\n<br/>at javax.servlet.http.HttpServlet.service(HttpServlet.java:847)\n<br/>at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:295)\n<br/>at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)\n<br/>at br.gov.tcu.arquitetura.util.jsf.ie.IEModoCompatibilidadeFilter.doFilterInternal(IEModoCompatibilidadeFilter.java:32)\n<br/>at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)\n<br/>at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246)\n<br/>at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)\n<br/>at br.gov.tcu.arquitetura.servlet.filter.FiltroArquiteturalAbstrato.doFilter(FiltroArquiteturalAbstrato.java:65)\n<br/>at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246)\n<br/>at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)\n<br/>at br.gov.tcu.arquitetura.servlet.filter.FiltroArquiteturalAbstrato.doFilter(FiltroArquiteturalAbstrato.java:65)\n<br/>at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246)\n<br/>at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)\n<br/>at br.gov.tcu.arquitetura.servlet.filter.FiltroArquiteturalAbstrato.doFilter(FiltroArquiteturalAbstrato.java:65)\n<br/>at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246)\n<br/>at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)\n<br/>at br.gov.tcu.arquitetura.servlet.filter.FiltroArquiteturalAbstrato.doFilter(FiltroArquiteturalAbstrato.java:65)\n<br/>at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246)\n<br/>at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)\n<br/>at br.gov.tcu.arquitetura.servlet.filter.excecao.ExceptionHandlerFilter.doFilter(ExceptionHandlerFilter.java:59)\n<br/>at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246)\n<br/>at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)\n<br/>at com.ocpsoft.pretty.PrettyFilter.doFilter(PrettyFilter.java:145)\n<br/>at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246)\n<br/>at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)\n<br/>at br.gov.tcu.arquitetura.servlet.filter.FiltroArquiteturalAbstrato.doFilter(FiltroArquiteturalAbstrato.java:65)\n<br/>at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246)\n<br/>at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)\n<br/>at com.ocpsoft.pretty.PrettyFilter.doFilter(PrettyFilter.java:145)\n<br/>at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246)\n<br/>at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)\n<br/>at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)\n<br/>at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:118)\n<br/>at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:84)\n<br/>at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)\n<br/>at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113)\n<br/>at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)\n<br/>at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:103)\n<br/>at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)\n<br/>at br.gov.tcu.arquitetura.spring.config.security.AnonymousAuthenticationFilterImpl.doFilter(AnonymousAuthenticationFilterImpl.java:87)\n<br/>at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)\n<br/>at br.gov.tcu.arquitetura.spring.config.security.LoginIntegradoAuthenticationProviderFilter.doFilter(LoginIntegradoAuthenticationProviderFilter.java:103)\n<br/>at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)\n<br/>at org.springframework.security.web.jaasapi.JaasApiIntegrationFilter.doFilter(JaasApiIntegrationFilter.java:91)\n<br/>at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)\n<br/>at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:154)\n<br/>at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)\n<br/>at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:45)\n<br/>at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)\n<br/>at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilter(BasicAuthenticationFilter.java:150)\n<br/>at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)\n<br/>at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:199)\n<br/>at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)\n<br/>at br.gov.tcu.arquitetura.spring.config.security.TokenJwtAuthenticationProviderFilter.doFilter(TokenJwtAuthenticationProviderFilter.java:60)\n<br/>at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)\n<br/>at org.springframework.security.web.authentication.preauth.AbstractPreAuthenticatedProcessingFilter.doFilter(AbstractPreAuthenticatedProcessingFilter.java:107)\n<br/>at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)\n<br/>at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:110)\n<br/>at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)\n<br/>at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:50)\n<br/>at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)\n<br/>at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)\n<br/>at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87)\n<br/>at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)\n<br/>at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:192)\n<br/>at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:160)\n<br/>at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:344)\n<br/>at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:261)\n<br/>at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246)\n<br/>at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)\n<br/>at org.springframework.orm.jpa.support.OpenEntityManagerInViewFilter.doFilterInternal(OpenEntityManagerInViewFilter.java:178)\n<br/>at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)\n<br/>at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246)\n<br/>at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)\n<br/>at org.primefaces.webapp.filter.FileUploadFilter.doFilter(FileUploadFilter.java:98)\n<br/>at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246)\n<br/>at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)\n<br/>at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:231)\n<br/>at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:149)\n<br/>at org.jboss.as.jpa.interceptor.WebNonTxEmCloserValve.invoke(WebNonTxEmCloserValve.java:50)\n<br/>at org.jboss.as.jpa.interceptor.WebNonTxEmCloserValve.invoke(WebNonTxEmCloserValve.java:50)\n<br/>at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:169)\n<br/>at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:145)\n<br/>at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:97)\n<br/>at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:102)\n<br/>at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344)\n<br/>at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:856)\n<br/>at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:653)\n<br/>at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:926)\n<br/>at java.lang.Thread.run(Thread.java:745)\nCaused by: org.springframework.beans.TypeMismatchException: Failed to convert value of type 'java.lang.String' to required type 'java.lang.Long'; nested exception is java.lang.NumberFormatException: For input string: \"v1_AC03DAE31D72A8375A91FE25A70139285812F509841ABB074944F1771414698CA7D64500ED376171E6E2779A439CCB608452419544CA779D11A963297FD2CF6D620A9E7DDDBB5AD58ADF23F2D4AD3D3F8AAE85FD8F29829F9C51B188260730E912DF5E751F5D300004EF01410A1A92ADF6652F6F00641B22FBD565D842FA791924BFD237D4D93EB3D39B1D754D28CCEC7E5B595753E8836C68B7A1641D9DDB0777C1DCE63FA710BB992A89BA60BA63E5415A34135D460D0366C0F3508DEBCFBB31EB41F3E621A8401CEC54B1DC84BA607CCD96975EA7DB5AEF32E83447D525F3DFEDE3A745C75D89B92CBC09B94E0B16D12141ABC78044DB3627D888251B48E9B5093EA7AC90168A6B7335EC1FBC292B7DDD0C597E2C5EC6C93144B45C173DD3CDA6BFD3F93AEBC57E5B595753E8836C\"\n<br/>at org.springframework.beans.TypeConverterSupport.doConvert(TypeConverterSupport.java:77)\n<br/>at org.springframework.beans.TypeConverterSupport.convertIfNecessary(TypeConverterSupport.java:47)\n<br/>at org.springframework.validation.DataBinder.convertIfNecessary(DataBinder.java:604)\n<br/>at org.springframework.web.method.annotation.AbstractNamedValueMethodArgumentResolver.resolveArgument(AbstractNamedValueMethodArgumentResolver.java:104)\n<br/>at org.springframework.web.method.support.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:77)\n<br/>at org.springframework.web.method.support.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:162)\n<br/>at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:129)\n<br/>at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)\n<br/>at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:776)\n<br/>at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:705)\n<br/>at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)\n<br/>at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)\n<br/>... 95 more\nCaused by: java.lang.NumberFormatException: For input string: \"v1_AC03DAE31D72A8375A91FE25A70139285812F509841ABB074944F1771414698CA7D64500ED376171E6E2779A439CCB608452419544CA779D11A963297FD2CF6D620A9E7DDDBB5AD58ADF23F2D4AD3D3F8AAE85FD8F29829F9C51B188260730E912DF5E751F5D300004EF01410A1A92ADF6652F6F00641B22FBD565D842FA791924BFD237D4D93EB3D39B1D754D28CCEC7E5B595753E8836C68B7A1641D9DDB0777C1DCE63FA710BB992A89BA60BA63E5415A34135D460D0366C0F3508DEBCFBB31EB41F3E621A8401CEC54B1DC84BA607CCD96975EA7DB5AEF32E83447D525F3DFEDE3A745C75D89B92CBC09B94E0B16D12141ABC78044DB3627D888251B48E9B5093EA7AC90168A6B7335EC1FBC292B7DDD0C597E2C5EC6C93144B45C173DD3CDA6BFD3F93AEBC57E5B595753E8836C\"\n<br/>at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)\n<br/>at java.lang.Long.parseLong(Long.java:441)\n<br/>at java.lang.Long.valueOf(Long.java:540)\n<br/>at org.springframework.util.NumberUtils.parseNumber(NumberUtils.java:196)\n<br/>at org.springframework.beans.propertyeditors.CustomNumberEditor.setAsText(CustomNumberEditor.java:113)\n<br/>at org.springframework.beans.TypeConverterDelegate.doConvertTextValue(TypeConverterDelegate.java:449)\n<br/>at org.springframework.beans.TypeConverterDelegate.doConvertValue(TypeConverterDelegate.java:422)\n<br/>at org.springframework.beans.TypeConverterDelegate.convertIfNecessary(TypeConverterDelegate.java:195)\n<br/>at org.springframework.beans.TypeConverterDelegate.convertIfNecessary(TypeConverterDelegate.java:107)\n<br/>at org.springframework.beans.TypeConverterSupport.doConvert(TypeConverterSupport.java:64)\n<br/>... 106 more\n",
  "mensagens": [
    {
      "texto": "Não foi possível finalizar a operação. Uma mensagem automática foi enviada para a área técnica responsável. Caso o problema persista, entre em contato com a Central de Serviços de TI (0800-644-1500) e informe a(s) sigla(s): SEGURANCA_010857. O atendente fará o encaminhamento e/ou priorização de sua manifestação."
    }
  ]
}

**Comment by nmschumacher** [comment]
Caro @Bonissauro,

Testei este serviço que reativa um usuário que foi excluído por meio do delete utilizando os parâmetros de e-mail e senha e funcionou como esperado, ele foi reativado.

Percebi que em sua pilha de erro tem a seguinte mensagem: 

> Caused by: org.springframework.beans.TypeMismatchException: Failed to convert value of type 'java.lang.String' to required type 'java.lang.Long'; nested exception is java.lang.NumberFormatException

E logo depois mostra seu _appToken_. Pelo que entendi, você informou o _appToken_ no lugar do _appIdentifier_. O _appToken_ é uma string e não é um parâmetro para o serviço de reativação, mas o _appIdentifier_ de fato é apenas um valor numérico do tipo Long, como informa o erro, pois é o código do aplicativo (em outros endpoints ele pode aparecer como _codAplicativo_ - isso será padronizado em outro momento). 

Peço-lhe, gentilmente, que verifique se de fato os argumentos informados correspondem aos da [documentação](https://github.com/AppCivicoPlataforma/AppCivico/blob/master/MetamodeloAPI.md#reativar-cadastro).

Att.

Equipe do [Desafio de Aplicativos Cívicos](http://portal.tcu.gov.br/desafio-aplicativos-civicos/o-desafio/).

**Comment by Bonissauro** [comment]
Foi uma das minhas varias tentativas, talvez.

Vou testar mais uma vez hoje à noite.

Obrigado, por enquanto.

> Em 13 de out de 2016, à(s) 11:19, nmschumacher notifications@github.com escreveu:
> 
> Percebi
