### ISSUE TITLE
Criar uma operação que crie uma postagem e um PRIMEIRO conteúdo

### ISSUE THREAD

**Issue by Bonissauro** [AppCivicoPlataforma/AppCivico#49]
Já existe um serviço que cria uma nova postagem, assim como também existe um que cria um novo conteúdo onde devemos referenciar a postagem à qual queremos incluir o conteúdo. 

Acontece que, de acordo com meus requisitos, 100% das vezes preciso gravar um conteúdo ao mesmo tempo em que preciso fazer já a primeira postagem. Resultado: preciso fazer SEMPRE duas chamadas (fazê-las assíncronas não resolve o problema, já que para a segunda chamada, preciso de informações do retorno da primeira - o código da postagem gerada).

Por isso, sugiro a criação de um serviço em que eu envie de uma vez só os dados da postagem e do primeiro conteúdo da postagem, o que economizaria sobremaneira o tempo de resposta do Aplicativo para o usuário, já que tudo seria resolvido na primeira chamada.

**Comment by SkiaBr23** [comment]
@Bonissauro,

Obrigado pela sugestão! Iremos implementar um novo _endpoint_ de criação de postagem com conteúdo. Aviso por aqui quando for publicado.

Atenciosamente,

Equipe do [Desafio de Aplicativos Cívicos](http://portal.tcu.gov.br/desafio-aplicativos-civicos/o-desafio/).

**Comment by Bonissauro** [comment]
Excelente! Temos chance de ter isso a tempo do prazo de entrega do App do Desafio Cívico?

Abraço!

On Thu, Oct 13, 2016 at 11:58 AM -0300, "Rafael Costa" notifications@github.com wrote:

@Bonissauro,

Obrigado pela sugestão! Iremos implementar um novo endpoint de criação de postagem com conteúdo. Aviso por aqui quando for publicado.

Atenciosamente,

Equipe do Desafio de Aplicativos Cívicos.

**Comment by SkiaBr23** [comment]
@Bonissauro,

Tem sim.

**Comment by SkiaBr23** [comment]
@Bonissauro,

Já está disponivel o [novo endpoint de criação de postagem com conteúdo inicial](http://mobile-aceite.tcu.gov.br/appCivicoRS/swagger/index.html?url=/appCivicoRS/v2/api-docs#!/postagens/cadastrarPostagemComConteudoUsingPOST). Peço que verifique a documentação via Swagger e faça alguns testes pra saber se resolve seu problema. Aguardo seu feedback!

Atenciosamente,

Equipe do [Desafio de Aplicativos Cívicos](http://portal.tcu.gov.br/desafio-aplicativos-civicos/o-desafio/).

**Comment by Bonissauro** [comment]
@SkiaBr23 Já resolveu boa parte do problema e me quebrou um galhão. Nota oito. 

Pra ganhar um nove, o endpoint poderia retornar, ao invés de "postagem já cadastrada", o link do conteúdo gerado na base da NC. Com isso, posso chegar ao link da postagem também, que são informações que meu app armazena localmente.

Agora, prum DEZ, daqueles de dar orgulho, o endpoint poderia retornar os dois links: o da postagem e o do conteúdo. Aí sim, seria pra glorificar de pé. Kkkkk!!!

Abraço e muito obrigado, por enquanto!

**Comment by SkiaBr23** [comment]
@Bonissauro,

Para melhorar o retorno desse _endpoint_, alterei o link devolvido para a URL do conteúdo criado. A partir dessa URL, que seria algo assim:

**.../appCivicoRS/rest/postagens/COD_POSTAGEM/conteudos/COD_CONTEUDO**

Essa URL é referente ao conteúdo criado na requisição, porém se você pegar esse valor e remover a substring "**/conteudos/COD_CONTEUDO**", você terá o link da postagem. 

Obs: Essa informação não é passada pela mensagem da resposta, e sim no header de resposta "_Location_". Via [Swagger](http://mobile-aceite.tcu.gov.br/appCivicoRS/swagger/index.html?url=/appCivicoRS/v2/api-docs#!/postagens/cadastrarPostagemComConteudoUsingPOST) você pode visualizar os headers de resposta e seus valores.

Atenciosamente,

Equipe do [Desafio de Aplicativos Cívicos](http://portal.tcu.gov.br/desafio-aplicativos-civicos/o-desafio/).
