### ISSUE TITLE
Paginação de recursos

### ISSUE THREAD

**Issue by alvarowolfx** [AppCivicoPlataforma/AppCivico#5]
Nenhum dos recursos possui parâmetros de paginação dos resultados. Seria interessante na listagem de remédios por exemplo pois não sei quantos resultados vai ser retornados, me obrigando a colocar um valor alto no parâmetro de quantidade de retorno.

**Comment by LucianoPAlmeida** [comment]
Olá @alvarowolfx 

Estamos analizando a possibilidade dessa inclusão. Retornaremos assim que possível.
Agradecemos pelo feedback.

**Comment by SkiaBr23** [comment]
Olá @alvarowolfx,

A paginação do endpoint de Remédios foi implementada e **já está disponível.** Estamos atualizando o restante da base de requisições para que também disponham desse campo adicional e avisaremos quando estiver disponível.

**Comment by SkiaBr23** [comment]
@alvarowolfx,

Os endpoints atualizados com o novo campo de paginação são os seguintes:

Metamodelo AppCivico:
- [x] Busca de pessoas
- [x] Busca de postagens
- [x] Busca de postagens por usuário
- [x] Busca de postagens no modelo timeline

Escolas:
- [x] Busca de escolas
- [x] Busca geográfica de escolas

Saúde:
- [x] Assistência Social
- [x] Assistência Social Especializada
- [x] Empregos
- [x] Estabelecimentos
- [x] Remédios

Incluindo alguns que já possuíam um campo de página. Todas essas atualizações já foram publicadas.

Caso seja necessário o uso da paginação em algum outro endpoint, podemos adicionar também.

Obrigado pela sugestão!

**Comment by alvarowolfx** [comment]
Valeu @SkiaBr23 👏
