### ISSUE TITLE
Talvez seja necessário mais um serviço

### ISSUE THREAD

**Issue by Bonissauro** [AppCivicoPlataforma/AppCivico#50]
Na regra do meu app, tenho uma “postagem pai” com uma ou mais “postagens filhas” efetuadas por outros usuários apontadas para essa "postagem-pai". Algo como as postagens do facebook que podem receber comentários de outros usuários.

Como faço para buscar uma postagem com todas suas postagens relacionadas? Tipo, buscar uma postagem-pai com todas suas filhas sendo retornadas num array. 

Procurei pelos serviços já existentes, mas o mais próximo que eu teria disso seria a busca por hashtag (veja bem, isso se eu praticamente "estuprar" o conceito de hashtag, kkkk!!!).

Tem jeito de implementar algo assim, com esse array de postagens não retornando apenas o link para as postagens, mas o seu CONTEÚDO em json? Esse detalhe seria importante no sentido de reduzir o número de requisições aos serviços da nuvem cívica. Imagine uma postagem que tenha dez postagens filhas. Uma chamada resolveria a questão, enquanto que, se me for enviado apenas o link da cada uma, como ora implementado na estrutura dos serviços, eu teria que fazer ONZE requisições: uma para a postagem-pai e mais dez para saber o conteúdo de cada postagem filha (isso se eu nao precisar do conteudo de cada postagem, o que acarretaria no minimo mais dez chamadas).

Estrutura ideal do novo servico:

entrada: link da postagem
saída: array com os dados de cada postagem filha e seus conteudos (1:1).

Agradeço antecipadamente a ajuda.

**Comment by SkiaBr23** [comment]
@Bonissauro,

Apesar de ter respondido parte do seu problema por email, vou reabrir essa _issue_ para esclarecer algumas alternativas pro resto do problema relatado aqui.

Esse problema de múltiplas requisições para tratar de postagens, postagens relacionadas e seus conteúdos **já foi discutido anteriormente** e criamos uma solução que otimiza um pouco o processo.

Via Swagger, sob o contexto de Postagens, [existe uma requisição chamada /postagens/timeline.](http://mobile-aceite.tcu.gov.br/appCivicoRS/swagger/index.html?url=/appCivicoRS/v2/api-docs#!/postagens/recuperarTimelineUsingGET) Essa solução retorna um tipo mais abrangente de busca de postagens, enviando tanto as informações completas do autor, todos os conteúdos da postagem buscada, uma lista com todas as postagens filhas dela, e uma lista de tipos das postagens relacionadas (_Bastante coisa!_). 

Eis o modelo Java da resposta:

``` java
@ApiModel("Timeline")
public class DtoTimeline extends HalObject {

    private Long codPostagem;
    private Date dataHoraPostagem;
    private Long codTipoPostagem;
    private Long codObjetoDestino;
    private Long codTipoObjetoDestino;

    private Long codAutor;
    private String nomeAutor;
    private byte[] fotoPerfilAutor;

    private DtoConteudo[] conteudosSalvos;
    private DtoTipoPostagemRelacionada[] tipoPostagensRelacionadas;
    private DtoPostagem[] postagensRelacionadas;
}
```

No momento, a busca é feita de forma similar ao endpoint 'postagens', em que são utilizados parâmetros opcionais para filtrar os resultados, que são exibidos em ordem cronológica de postagem (como uma timeline).
- O primeiro bloco contém as informações padrão de uma postagem: seu código, data/hora, e códigos de objeto/tipos. 
- No próximo, informações de código de autor, nome e a foto de perfil também são enviados.
- No último bloco, são enviados os conteúdos da postagem (agora abertos ao invés de apenas links), 
  todas as postagens relacionadas (abertas) e uma nova estrutura\* para contabilizar quantidades de postagens relacionadas.
  - Essa última estrutura exibe uma lista de pares que determinam quantas postagens de determinado tipo são relacionadas à certa postagem. Tomando como exemplo uma postagem que tem 5 comentários (TipoPostagem = 1) e 10 likes (TipoPostagem=2), sua lista seria da seguinte forma (JSON, apenas dessa parte da estrutura):

``` json
"tipoPostagensRelacionadas": [
      {
        "codTipoPostagem": 0001,
        "qteTipoPostagem": 5,
        "links": []
      },
      {
        "codTipoPostagem": 0002,
        "qteTipoPostagem": 10,
        "links": []

      }   
    ]
```

Uma vez que todas as postagens relacionadas estão sendo retornadas, a lógica para saber se o usuário deu like na postagem ou não já pode ser feita com as informações que esse endpoint está enviando.

Essa solução não retorna os conteúdos abertos das postagens filhas, mas já ajuda bastante dependendo da estrutura da sua aplicação. Vou postar esse guia [no nosso FAQ](https://github.com/AppCivicoPlataforma/AppCivico/wiki/%5BFAQ%5D-Perguntas-Frequentes) e na [documentação do Metamodelo.](https://github.com/AppCivicoPlataforma/AppCivico/blob/master/MetamodeloAPI.md)

Atenciosamente,

Equipe do [Desafio de Aplicativos Cívicos](http://portal.tcu.gov.br/desafio-aplicativos-civicos/o-desafio/).

**Comment by Bonissauro** [comment]
Excelente, @SkiaBr23 ! 

Vou me debruçar sobre isso no fim-de-semana.

Obrigado!

**Comment by SkiaBr23** [comment]
Qualquer outra dúvida/problema nas postagens ou na plataforma em geral, é só abrir mais uma issue por aqui. Assim, geramos soluções que podem ajudar também os outros desenvolvedores. =)

Atenciosamente,

Equipe do [Desafio de Aplicativos Cívicos](http://portal.tcu.gov.br/desafio-aplicativos-civicos/o-desafio/).
