### ISSUE TITLE
Logomarca Aplicacativos Civicos

### ISSUE THREAD

**Issue by matbrandao** [AppCivicoPlataforma/AppCivico#51]
Boa tarde, no edital há uma menção a necessidade de utilizar a logomarca que vocês irão disponibilizar, mas não encontrei essa logomarca em nenhum lugar. Cheguei a enviar um email para os email citados no edital, mas não obtive nenhuma resposta.  Vocês podem me tirar essa dúvida de como conseguir as imagens?

E mais uma dúvida, a logomarca deve ser utilizada como o ícone do aplicativo?

Obrigado

**Comment by ragulhari** [comment]
@matbrandao também tenho essa dúvida, porém relendo o edital entendi que apenas os que serão contemplados deverão ter esse banner. Tentei confirmar essa informação e também não tive retorno, por isso também gostaria de saber para finalizar o aplicativo.

**Comment by eduardobreno** [comment]
As imagens foram disponibilizadas dia 11 na parte de noticias do site

http://portal.tcu.gov.br/desafio-aplicativos-civicos/noticias/

**Comment by matbrandao** [comment]
@eduardobreno Salva vidas! Mas hein, vocês entenderam como deve ser feita a utilização dessas logomarcas?

**Comment by SkiaBr23** [comment]
@matbrandao @ragulhari 

De acordo com o item 11.3 do [edital do Desafio de Aplicativos Cívicos](http://portal.tcu.gov.br/lumis/portal/file/fileDownload.jsp?fileId=8A8182A2561DF3F5015695395F263C64),
- **11.3.** Deverá ser feita menção ao Concurso DESAFIO DE APLICATIVOS CÍVICOS: CONTROLE SOCIAL DIGITAL-2016 e à sua entidade realizadora, no caso o Tribunal de Contas da União, em todos os aplicativos contemplados neste concurso. A menção deve ser feita **na tela de créditos, na tela de abertura do aplicativo, no texto e na tag da loja virtual.** Deverá ser utilizada a logomarca do DESAFIO DE APLICATIVOS CÍVICOS: CONTROLE SOCIAL DIGITAL-2016 e do TCU, que serão disponibilizadas pelo TCU.

Irei confirmar na segunda sobre a necessidade dessa menção para todos os aplicativos ou apenas os contemplados.

Atenciosamente,

Equipe do [Desafio de Aplicativos Cívicos](http://portal.tcu.gov.br/desafio-aplicativos-civicos/o-desafio/).

**Comment by kzin** [comment]
É necessário ter uma tela de créditos?

**Comment by AppCivicoPlataforma** [comment]
@matbrandao e @ragulhari,

> Irei confirmar na segunda sobre a necessidade dessa menção para todos os aplicativos

Sim. Todos os aplicativos submetidos ao  [Desafio de Aplicativos Cívicos](http://portal.tcu.gov.br/desafio-aplicativos-civicos/o-desafio/) **devem** fazer menção às logomarcas. 

Atenciosamente,

Equipe do [Desafio de Aplicativos Cívicos](http://portal.tcu.gov.br/desafio-aplicativos-civicos/o-desafio/).

**Comment by AppCivicoPlataforma** [comment]
@kzin ,

Sim. É necessária a **tela de créditos** contendo as logomarcas mencionadas pelos colegas nesta thread.

Atenciosamente,

Equipe do [Desafio de Aplicativos Cívicos](http://portal.tcu.gov.br/desafio-aplicativos-civicos/o-desafio/).
