### ISSUE TITLE
Busca de Estabelecimentos por nomeFantasia

### ISSUE THREAD

**Issue by matbrandao** [AppCivicoPlataforma/AppCivico#52]
Boa tarde, seria possivel vocês disponibilizarem um endpoint de busca de estabelecimentos utilizando o parâmetro nomeFantasia? Assim os usuários poderiam buscar um estabelecimento por nome.

Obrigado

**Comment by SkiaBr23** [comment]
@matbrandao,

Obrigado pela sugestão! Já está disponível na [busca genérica de Estabelecimentos ](http://mobile-aceite.tcu.gov.br/appCivicoRS/swagger/index.html?url=/mapa-da-saude/v2/api-docs#!/estabelecimentos/recuperarEstabelecimentosUsingGET)o novo parâmetro opcional de _nomeFantasia_.

Atenciosamente,

Equipe do [Desafio de Aplicativos Cívicos](http://portal.tcu.gov.br/desafio-aplicativos-civicos/o-desafio/).
