### ISSUE TITLE
[EDITAL] Retificação - PRAZO DE ENVIO DOS APLICATIVOS

### ISSUE THREAD

**Issue by AppCivicoPlataforma** [AppCivicoPlataforma/AppCivico#55]
Prezados @luciocamilo, @Eversonbadaro, @thiagonunes-silva, @luarfaria, @d1hacker, @cptullio, @geraugu, @matbrandao, @allantorres, @eduardobreno, @LoveraSantiago, @jrpacheco, @ragulhari, @andre991, @caduvieira, @jardelnovaes, @joaopaulopereira, @alvarowolfx, @nilsonivano @Bonissauro, @marcelopacote e @agnoldo

Em virtude de sua atividade recente na [plataforma GitHub](https://github.com/AppCivicoPlataforma/AppCivico), identificamos que você está participando do _[Desafio de Aplicativos Cívicos](http://portal.tcu.gov.br/desafio-aplicativos-civicos/o-desafio/)_.

Informamos, pois, que o [edital do Desafio](http://portal.tcu.gov.br/lumis/portal/file/fileDownload.jsp?fileId=8A8182A157C4E4100157D381E2BA1CF5) foi retificado.  A principal mudança reza sobre a data de envio dos aplicativos que foi **adiada para data limite de 15/11/2016**.

Sugerimos a [leitura do edital](http://portal.tcu.gov.br/lumis/portal/file/fileDownload.jsp?fileId=8A8182A157C4E4100157D381E2BA1CF5) e o acompanhamento da [página do Desafio](http://portal.tcu.gov.br/desafio-aplicativos-civicos/o-desafio/).

Atenciosamente,
Equipe do [Desafio de Aplicativos Cívicos](http://portal.tcu.gov.br/desafio-aplicativos-civicos/o-desafio/).

**Comment by geraugu** [comment]
Maravilha!

**Comment by luciocamilo** [comment]
Como ficam os envios dos documentos que não podem ser retificados pela
plataforma?

Em 18 de outubro de 2016 16:35, AppCivicoPlataforma <
notifications@github.com> escreveu:

**Comment by AppCivicoPlataforma** [comment]
@luciocamilo ,

Você recebeu resposta do questionamento acima por e-mail. Confirma?

[]´s

**Comment by luciocamilo** [comment]
Sobre este ponto não fui respondido ainda.

Em 25 de out de 2016 09:43, "AppCivicoPlataforma" notifications@github.com
escreveu:

**Comment by AppCivicoPlataforma** [comment]
@luciocamilo,

> Como ficam os envios dos documentos que não podem ser retificados pela plataforma?

A plataforma agora permite a reenvio dos documentos.  Obséquio seguir as etapas [descritas no tutorial](https://drive.google.com/file/d/0B-NBmgxn2OjNelFGUDVSWExiNUk/view).

Atenciosamente,

Equipe do [Desafio de Aplicativos Cívicos](http://portal.tcu.gov.br/desafio-aplicativos-civicos/o-desafio/).
