### ISSUE TITLE
Possibilidade filtrar por mais de uma categoria e mais alguns filtros

### ISSUE THREAD

**Issue by raphaelporto** [AppCivicoPlataforma/AppCivico#56]
Boa tarde,

Gostaria de saber se seria possível acrescentar a possibilidade de filtrar por mais de uma categoria um estabelecimento de saúde, atualmente só é possível passar uma categoria por parâmetro.

Além disso, seria pertinente acrescentar filtros para os campos "VinculoSus" e "retencao" (informar os valores possíveis para rentenção).

Atenciosamente,

**Comment by SkiaBr23** [comment]
@raphaelporto,

Esse tipo de busca com parâmetros multivalorados já foi discutida anteriormente, e não será implementada na **versão atual** da API. Por enquanto, apenas buscas com parâmetros únicos.

Já estão disponíveis na busca de Estabelecimentos os dois novos filtros por _retencao_ e _vinculoSus_ requisitados. Atualizei a [documentação do endpoint](https://github.com/AppCivicoPlataforma/AppCivico/blob/master/EstabelecimentosAPI.md#estabelecimentos) com os valores possíveis para o parâmetro _retencao_ assim como [via Swagger](http://mobile-aceite.tcu.gov.br/appCivicoRS/swagger/index.html?url=/mapa-da-saude/v2/api-docs#!/estabelecimentos/recuperarEstabelecimentosUsingGET).

Atenciosamente,

Equipe do [Desafio de Aplicativos Cívicos](http://portal.tcu.gov.br/desafio-aplicativos-civicos/o-desafio/).

**Comment by raphaelporto** [comment]
@SkiaBr23 

Muito obrigado. Poderia acrescentar os mesmos filtros (retencao e vinculoSus) para a consulta geo referenciada por latitude e longitude? Esqueci de mencionar.

Atenciosamente,

**Comment by SkiaBr23** [comment]
@raphaelporto,

Adicionei os filtros na [consulta por localização](http://mobile-aceite.tcu.gov.br/appCivicoRS/swagger/index.html?url=/mapa-da-saude/v2/api-docs#!/estabelecimentos/recuperarEstabelecimentosPorLocalizacaoUsingGET) como solicitado. Obrigado pela sugestão!

Atenciosamente,

Equipe do [Desafio de Aplicativos Cívicos](http://portal.tcu.gov.br/desafio-aplicativos-civicos/o-desafio/).
