### ISSUE TITLE
Aumentar tamanho dos campos para armazenar os tokens de Pessoa no Metamodelo

### ISSUE THREAD

**Issue by raphaelporto** [AppCivicoPlataforma/AppCivico#57]
Atualmente os campos dedicados a armazenar os Tokens na tabela PESSOA do Metamodelo estão definidos como VARCHAR(255), no entanto, os tokens que verifiquei em testes tem tamanho muito superior a isso. A própria recomendação do facebook é deixar que esse campo tenha valor variável sem limites de tamanho.

> Comprimento do token de acesso
> 
> O comprimento esperado de todos os tipos de token de acesso mudará ao longo do tempo à medida que o Facebook faz alterações no que é armazenado neles e como eles são codificados. Você pode esperar que eles aumentem e reduzam com o tempo. Use um tipo de dados de comprimento variável sem um tamanho máximo específico para armazenar tokens de acesso.

Fonte: https://developers.facebook.com/docs/facebook-login/access-tokens/debugging-and-error-handling

**Comment by SkiaBr23** [comment]
@raphaelporto,

Obrigado por reportar esse problema! Já está em andamento essa alteração do tamanho do campo dos tokens. Aviso por aqui quando for publicado.

Atenciosamente,

Equipe do [Desafio de Aplicativos Cívicos](http://portal.tcu.gov.br/desafio-aplicativos-civicos/o-desafio/).

**Comment by SkiaBr23** [comment]
@raphaelporto,

O tamanho dos campos de tokens da tabela PESSOA foi aumentado para VARCHAR(3000). Isso resolve o seu problema? Aguardo feedback.

Atenciosamente,

Equipe do [Desafio de Aplicativos Cívicos](http://portal.tcu.gov.br/desafio-aplicativos-civicos/o-desafio/).

**Comment by AppCivicoPlataforma** [comment]
@raphaelporto,

Reiteramos, pois, o questionamento. O aumento do campo para VARCHAR(3000) atendeu sua necessidade?

Atenciosamente,

Equipe do [Desafio de Aplicativos Cívicos](http://portal.tcu.gov.br/desafio-aplicativos-civicos/o-desafio/).

**Comment by raphaelporto** [comment]
@AppCivicoPlataforma , @SkiaBr23 

Desculpem a demora no retorno.  Considerando o que diz o facebook sobre o token de acesso deles, não tenho como afirmar que será suficiente, no entanto, encontrei uma forma de evitar qualquer problema em relação a essa restrição. Dessa forma, a mudança do campo atende a minha necessidade.

Muito obrigado.
