### ISSUE TITLE
Problema ao confirmar o cadastro no portal do TCU

### ISSUE THREAD

**Issue by kzin** [AppCivicoPlataforma/AppCivico#58]
Prezados,

Hoje fui me cadastrar no portal do tcu para enviar a proposta e ao clicar no link enviado pelo email de confirmação o seguinte erro ocorreu.

`Não foi possível finalizar a operação. Uma mensagem automática foi enviada para a área técnica responsável. Caso o problema persista, entre em contato com a Central de Serviços de TI (0800-6441500) e informe a sigla: TCU_PUB_120816. O atendente fará o encaminhamento e/ou priorização de sua manifestação.
`
Att,
Obrigado

**Comment by AppCivicoPlataforma** [comment]
@kzin ,

Graças ao teu aviso percebemos um problema no [_portal_ ](http://portal.tcu.gov.br/cidadao/cidadao.htm) que afetava o cadastro de todos os usuários. Agradecemos o apoio.

O problema foi corrigido e haverá atualização do portal esta madrugada. Peço-lhe que, por favor, faça nova tentativa no fim de semana.

Atenciosamente,

Equipe do [Desafio de Aplicativos Cívicos](http://portal.tcu.gov.br/desafio-aplicativos-civicos/o-desafio/).
