### ISSUE TITLE
Dúvida sobre "tipo de objeto"

### ISSUE THREAD

**Issue by julianesansil** [AppCivicoPlataforma/AppCivico#59]
Olá.

Gostaria de entender melhor o "tipo de objeto" do metamodelo, que pode ser relacionado ao tipo da postagem.
**Esse tipo de objeto deve ser utilizado somente quando a postagem é de feedback/avaliação?**

Vi na FAQ que existem tipos de objetos pré-cadastrados (de 100 a 500). Nenhum, porém, é relacionado à escola.
Considerando que vocês recomendam que utilizemos somente esses tipos pré-cadastrados, **vocês poderiam criar um tipo relacionado à escola?!**

Obrigada!

**Comment by monilouise** [comment]
@julianesansil 

Pode utilizar o tipo 1 Escolas (FAQ atualizada).

Atenciosamente,
Equipe do Desafio de Aplicativos Cívicos.

**Comment by julianesansil** [comment]
Só pra confirmar...
Esse tipo de objeto deve ser utilizado somente quando a postagem é de feedback/avaliação?

Obrigada! :)

**Comment by monilouise** [comment]
Até o momento sim, apenas para feedback/avaliação.

Atenciosamente,
Equipe do Desafio de Aplicativos Cívicos.
