### ISSUE TITLE
Cadastro do Aplicativo

### ISSUE THREAD

**Issue by jardelnovaes** [AppCivicoPlataforma/AppCivico#6]
O cadastro do aplicativo no link http://mobile-aceite.tcu.gov.br/appCivicoWeb/web/externo/#/aplicativos estava com "BUG" dizendo que havia problemas com a Internet, então cadastrei uma descrição qualquer e consegui salvar, porém não há a opção de atualizar a descrição.

Seria interessante ter.

**Comment by LucianoPAlmeida** [comment]
Olá @jardelnovaes ,

Estamos corrigindo esse problema. Há sim a opção de alterar a descrição do aplicativo basta apenas selecionar o aplicativo na lista lateral, e o formulário muda para o formato de atualizar o aplicativo. 
Agradecemos o feedback, tentaremos resolver o problema o mais rápido possível.

**Comment by jardelnovaes** [comment]
Agora consegui, muito obrigado.
