### ISSUE TITLE
Requisição não esta respondendo

### ISSUE THREAD

**Issue by weslleyng** [AppCivicoPlataforma/AppCivico#60]
![captura de tela 31](https://cloud.githubusercontent.com/assets/7536661/19676479/9e9e20b8-9a62-11e6-89a6-ee2877c5c691.png)
Uma requisição do [Estabelecimentos de Saúde](https://github.com/AppCivicoPlataforma/AppCivico/blob/master/EstabelecimentosAPI.md#estabelecimentos-de-sa%C3%BAde)  mais especifica esta aqui [GET - /rest/estabelecimentos/latitude/{latitude}/longitude/{longitude}/raio/{raio}](https://github.com/AppCivicoPlataforma/AppCivico/blob/master/EstabelecimentosAPI.md#estabelecimentos-georreferenciados), ela não esta respondendo corretamente, porem, pelo [Swagger API](http://mobile-aceite.tcu.gov.br/appCivicoRS/swagger/index.html?url=/mapa-da-saude/v2/api-docs#!/estabelecimentos/recuperarEstabelecimentosPorLocalizacaoUsingGET) ela responde corretamente, mas em aplicação e até msm por outros programas que uso para testas requisições, ela não responde em alguns como por exemplo [Advanced REST client](https://chrome.google.com/webstore/detail/advanced-rest-client/hgmloofddffdnphfgcellkdfbfbjeloo/reviews?hl=en-US&utm_source=ARC)

A url testada foi exatamente esta 

> http://mobile-aceite.tcu.gov.br:80/mapa-da-saude/rest/estabelecimentos/latitude/-3.00945744/longitude/-59.98819106/raio/80?quantidade=10

**Comment by nmschumacher** [comment]
Prezado @weslleyng,

De fato, percebemos que as consultas não estão rápidas. Sugerimos que para a API citada - [Advanced REST client](https://chrome.google.com/webstore/detail/advanced-rest-client/hgmloofddffdnphfgcellkdfbfbjeloo/reviews?hl=en-US&utm_source=ARC) - seja aumentado o tempo de _timeout_ para 60 segundos. Basta ir em **Settings (no canto inferior esquerdo) > Request timeout** e alterar o valor do campo.

Paralelamente, estamos verificando uma forma de agilizar as consultas. Obrigado pelo feedback.

Att.

Equipe do [Desafio de Aplicativos Cívicos](http://portal.tcu.gov.br/desafio-aplicativos-civicos/o-desafio/).
