### ISSUE TITLE
Erro 500

### ISSUE THREAD

**Issue by weslleyng** [AppCivicoPlataforma/AppCivico#61]
Erro 500 na seguinte URL
http://mobile-aceite.tcu.gov.br/mapa-da-saude/rest/estabelecimentos/latitude/-3.0096295/longitude/-59.9881472/raio/7.0?quantidade=30

segue log da falha

> O documento XML não está associado a estilos. A estrutura do documento está representada abaixo.
> <erroInfo>
> <dadosTecnicos>
> br.gov.tcu.arquitetura.util.excecao.ExcecaoNaoPrevista: SEGURANCA_053615 <br/>at br.gov.tcu.arquitetura.is.ws.rest.excecao.TratadorExcecaoNegocioArqref7EThrowable.tratarExcecao(TratadorExcecaoNegocioArqref7EThrowable.java:54) <br/>at br.gov.tcu.arquitetura.is.ws.rest.excecao.TratadorExcecaoNegocioArqref7EThrowable$$FastClassBySpringCGLIB$$f12bd73b.invoke(<generated>) <br/>at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) <br/>at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:717) <br/>at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) <br/>at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99) <br/>at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281) <br/>at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96) <br/>at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) <br/>at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:653) <br/>at br.gov.tcu.arquitetura.is.ws.rest.excecao.TratadorExcecaoNegocioArqref7EThrowable$$EnhancerBySpringCGLIB$$3489aa91.tratarExcecao(<generated>) <br/>at br.gov.tcu.arquitetura.is.ws.rest.excecao.RestExceptionHandler.tratarExcecaoGenerica(RestExceptionHandler.java:127) <br/>at sun.reflect.GeneratedMethodAccessor5776.invoke(Unknown Source) <br/>at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) <br/>at java.lang.reflect.Method.invoke(Method.java:606) <br/>at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221) <br/>at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137) <br/>at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110) <br/>at org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver.doResolveHandlerMethodException(ExceptionHandlerExceptionResolver.java:362) <br/>at org.springframework.web.servlet.handler.AbstractHandlerMethodExceptionResolver.doResolveException(AbstractHandlerMethodExceptionResolver.java:60) <br/>at org.springframework.web.servlet.handler.AbstractHandlerExceptionResolver.resolveException(AbstractHandlerExceptionResolver.java:138) <br/>at org.springframework.web.servlet.handler.HandlerExceptionResolverComposite.resolveException(HandlerExceptionResolverComposite.java:74) <br/>at org.springframework.web.servlet.DispatcherServlet.processHandlerException(DispatcherServlet.java:1183) <br/>at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1020) <br/>at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:971) <br/>at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893) <br/>at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:967) <br/>at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:858) <br/>at javax.servlet.http.HttpServlet.service(HttpServlet.java:734) <br/>at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:843) <br/>at javax.servlet.http.HttpServlet.service(HttpServlet.java:847) <br/>at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:295) <br/>at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) <br/>at br.gov.tcu.arquitetura.servlet.filter.FiltroArquiteturalAbstrato.doFilter(FiltroArquiteturalAbstrato.java:65) <br/>at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246) <br/>at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) <br/>at br.gov.tcu.arquitetura.servlet.filter.FiltroArquiteturalAbstrato.doFilter(FiltroArquiteturalAbstrato.java:65) <br/>at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246) <br/>at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) <br/>at br.gov.tcu.arquitetura.util.jsf.ie.IEModoCompatibilidadeFilter.doFilterInternal(IEModoCompatibilidadeFilter.java:32) <br/>at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) <br/>at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246) <br/>at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) <br/>at br.gov.tcu.arquitetura.servlet.filter.FiltroArquiteturalAbstrato.doFilter(FiltroArquiteturalAbstrato.java:65) <br/>at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246) <br/>at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) <br/>at br.gov.tcu.arquitetura.servlet.filter.FiltroArquiteturalAbstrato.doFilter(FiltroArquiteturalAbstrato.java:65) <br/>at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246) <br/>at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) <br/>at br.gov.tcu.arquitetura.servlet.filter.excecao.ExceptionHandlerFilter.doFilter(ExceptionHandlerFilter.java:59) <br/>at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246) <br/>at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) <br/>at com.ocpsoft.pretty.PrettyFilter.doFilter(PrettyFilter.java:145) <br/>at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246) <br/>at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) <br/>at br.gov.tcu.arquitetura.servlet.filter.FiltroArquiteturalAbstrato.doFilter(FiltroArquiteturalAbstrato.java:65) <br/>at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246) <br/>at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) <br/>at com.ocpsoft.pretty.PrettyFilter.doFilter(PrettyFilter.java:145) <br/>at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246) <br/>at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) <br/>at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) <br/>at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:118) <br/>at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:84) <br/>at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) <br/>at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113) <br/>at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) <br/>at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:103) <br/>at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) <br/>at br.gov.tcu.arquitetura.spring.config.security.AnonymousAuthenticationFilterImpl.doFilter(AnonymousAuthenticationFilterImpl.java:87) <br/>at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) <br/>at br.gov.tcu.arquitetura.spring.config.security.LoginIntegradoAuthenticationProviderFilter.doFilter(LoginIntegradoAuthenticationProviderFilter.java:103) <br/>at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) <br/>at org.springframework.security.web.jaasapi.JaasApiIntegrationFilter.doFilter(JaasApiIntegrationFilter.java:91) <br/>at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) <br/>at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:154) <br/>at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) <br/>at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:45) <br/>at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) <br/>at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilter(BasicAuthenticationFilter.java:150) <br/>at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) <br/>at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:199) <br/>at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) <br/>at br.gov.tcu.arquitetura.spring.config.security.TokenJwtAuthenticationProviderFilter.doFilter(TokenJwtAuthenticationProviderFilter.java:60) <br/>at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) <br/>at org.springframework.security.web.authentication.preauth.AbstractPreAuthenticatedProcessingFilter.doFilter(AbstractPreAuthenticatedProcessingFilter.java:107) <br/>at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) <br/>at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:110) <br/>at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) <br/>at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:50) <br/>at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) <br/>at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) <br/>at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87) <br/>at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) <br/>at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:192) <br/>at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:160) <br/>at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:344) <br/>at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:261) <br/>at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246) <br/>at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) <br/>at org.springframework.orm.jpa.support.OpenEntityManagerInViewFilter.doFilterInternal(OpenEntityManagerInViewFilter.java:178) <br/>at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) <br/>at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246) <br/>at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) <br/>at org.primefaces.webapp.filter.FileUploadFilter.doFilter(FileUploadFilter.java:98) <br/>at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246) <br/>at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) <br/>at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:231) <br/>at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:149) <br/>at org.jboss.as.jpa.interceptor.WebNonTxEmCloserValve.invoke(WebNonTxEmCloserValve.java:50) <br/>at org.jboss.as.jpa.interceptor.WebNonTxEmCloserValve.invoke(WebNonTxEmCloserValve.java:50) <br/>at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:169) <br/>at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:145) <br/>at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:97) <br/>at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:102) <br/>at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344) <br/>at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:856) <br/>at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:653) <br/>at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:926) <br/>at java.lang.Thread.run(Thread.java:745) Caused by: javax.persistence.PersistenceException: org.hibernate.exception.GenericJDBCException: Could not open connection <br/>at org.hibernate.ejb.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1387) <br/>at org.hibernate.ejb.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1310) <br/>at org.hibernate.ejb.QueryImpl.getResultList(QueryImpl.java:277) <br/>at br.gov.tcu.mapadasaude.dominio.estabelecimento.dao.DaoEstabelecimento.recuperarEstabelecimentosEmUmRaio(DaoEstabelecimento.java:113) <br/>at br.gov.tcu.mapadasaude.dominio.estabelecimento.dao.DaoEstabelecimento$$FastClassBySpringCGLIB$$1d014487.invoke(<generated>) <br/>at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) <br/>at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:717) <br/>at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) <br/>at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:85) <br/>at br.gov.tcu.arquitetura.tu.util.logging.ComponentLoggingAspect.monitorar(ComponentLoggingAspect.java:33) <br/>at br.gov.tcu.arquitetura.tu.util.logging.ComponentLoggingAspect.monitorarDAOs(ComponentLoggingAspect.java:23) <br/>at sun.reflect.GeneratedMethodAccessor5528.invoke(Unknown Source) <br/>at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) <br/>at java.lang.reflect.Method.invoke(Method.java:606) <br/>at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:621) <br/>at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:610) <br/>at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:68) <br/>at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) <br/>at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99) <br/>at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281) <br/>at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96) <br/>at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) <br/>at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) <br/>at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) <br/>at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:653) <br/>at br.gov.tcu.mapadasaude.dominio.estabelecimento.dao.DaoEstabelecimento$$EnhancerBySpringCGLIB$$7351ef33.recuperarEstabelecimentosEmUmRaio(<generated>) <br/>at br.gov.tcu.mapadasaude.webservices.rest.estabelecimento.Estabelecimentos.recuperarEstabelecimentosPorLocalizacao(Estabelecimentos.java:175) <br/>at sun.reflect.GeneratedMethodAccessor5582.invoke(Unknown Source) <br/>at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) <br/>at java.lang.reflect.Method.invoke(Method.java:606) <br/>at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221) <br/>at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137) <br/>at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110) <br/>at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:776) <br/>at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:705) <br/>at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) <br/>at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959) <br/>... 95 more Caused by: org.hibernate.exception.GenericJDBCException: Could not open connection <br/>at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:54) <br/>at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:124) <br/>at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:109) <br/>at org.hibernate.engine.jdbc.internal.LogicalConnectionImpl.obtainConnection(LogicalConnectionImpl.java:221) <br/>at org.hibernate.engine.jdbc.internal.LogicalConnectionImpl.getConnection(LogicalConnectionImpl.java:157) <br/>at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.connection(StatementPreparerImpl.java:56) <br/>at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$5.doPrepare(StatementPreparerImpl.java:159) <br/>at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:183) <br/>at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.prepareQueryStatement(StatementPreparerImpl.java:157) <br/>at org.hibernate.loader.Loader.prepareQueryStatement(Loader.java:1881) <br/>at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1858) <br/>at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1838) <br/>at org.hibernate.loader.Loader.doQuery(Loader.java:906) <br/>at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:348) <br/>at org.hibernate.loader.Loader.doList(Loader.java:2550) <br/>at org.hibernate.loader.Loader.doList(Loader.java:2536) <br/>at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2366) <br/>at org.hibernate.loader.Loader.list(Loader.java:2361) <br/>at org.hibernate.loader.custom.CustomLoader.list(CustomLoader.java:340) <br/>at org.hibernate.internal.SessionImpl.listCustomQuery(SessionImpl.java:1752) <br/>at org.hibernate.internal.AbstractSessionImpl.list(AbstractSessionImpl.java:232) <br/>at org.hibernate.internal.SQLQueryImpl.list(SQLQueryImpl.java:157) <br/>at org.hibernate.ejb.QueryImpl.getResultList(QueryImpl.java:268) <br/>... 129 more Caused by: java.sql.SQLException: javax.resource.ResourceException: IJ000453: Unable to get managed connection for java:/xadatasources/mapa-da-saudeDatasource <br/>at org.jboss.jca.adapters.jdbc.WrapperDataSource.getConnection(WrapperDataSource.java:151) <br/>at org.hibernate.ejb.connection.InjectedDataSourceConnectionProvider.getConnection(InjectedDataSourceConnectionProvider.java:70) <br/>at org.hibernate.internal.AbstractSessionImpl$NonContextualJdbcConnectionAccess.obtainConnection(AbstractSessionImpl.java:301) <br/>at org.hibernate.engine.jdbc.internal.LogicalConnectionImpl.obtainConnection(LogicalConnectionImpl.java:214) <br/>... 148 more Caused by: javax.resource.ResourceException: IJ000453: Unable to get managed connection for java:/xadatasources/mapa-da-saudeDatasource <br/>at org.jboss.jca.core.connectionmanager.AbstractConnectionManager.getManagedConnection(AbstractConnectionManager.java:417) <br/>at org.jboss.jca.core.connectionmanager.tx.TxConnectionManagerImpl.getManagedConnection(TxConnectionManagerImpl.java:368) <br/>at org.jboss.jca.core.connectionmanager.AbstractConnectionManager.allocateConnection(AbstractConnectionManager.java:491) <br/>at org.jboss.jca.adapters.jdbc.WrapperDataSource.getConnection(WrapperDataSource.java:143) <br/>... 151 more Caused by: javax.resource.ResourceException: IJ000658: Unexpected throwable while trying to create a connection: null <br/>at org.jboss.jca.core.connectionmanager.pool.mcp.SemaphoreArrayListManagedConnectionPool.getConnection(SemaphoreArrayListManagedConnectionPool.java:421) <br/>at org.jboss.jca.core.connectionmanager.pool.AbstractPool.getTransactionNewConnection(AbstractPool.java:486) <br/>at org.jboss.jca.core.connectionmanager.pool.AbstractPool.getConnection(AbstractPool.java:387) <br/>at org.jboss.jca.core.connectionmanager.AbstractConnectionManager.getManagedConnection(AbstractConnectionManager.java:354) <br/>... 154 more Caused by: javax.resource.ResourceException: Could not create connection <br/>at org.jboss.jca.adapters.jdbc.xa.XAManagedConnectionFactory.getXAManagedConnection(XAManagedConnectionFactory.java:525) <br/>at org.jboss.jca.adapters.jdbc.xa.XAManagedConnectionFactory.createManagedConnection(XAManagedConnectionFactory.java:434) <br/>at org.jboss.jca.core.connectionmanager.pool.mcp.SemaphoreArrayListManagedConnectionPool.createConnectionEventListener(SemaphoreArrayListManagedConnectionPool.java:834) <br/>at org.jboss.jca.core.connectionmanager.pool.mcp.SemaphoreArrayListManagedConnectionPool.getConnection(SemaphoreArrayListManagedConnectionPool.java:379) <br/>... 157 more Caused by: java.sql.SQLRecoverableException: ORA-01033: ORACLE initialization or shutdown in progress <br/>at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:440) <br/>at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:389) <br/>at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:382) <br/>at oracle.jdbc.driver.T4CTTIoauthenticate.processError(T4CTTIoauthenticate.java:427) <br/>at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:445) <br/>at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:191) <br/>at oracle.jdbc.driver.T4CTTIoauthenticate.doOSESSKEY(T4CTTIoauthenticate.java:390) <br/>at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:363) <br/>at oracle.jdbc.driver.PhysicalConnection.<init>(PhysicalConnection.java:536) <br/>at oracle.jdbc.driver.T4CConnection.<init>(T4CConnection.java:228) <br/>at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:32) <br/>at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:521) <br/>at oracle.jdbc.pool.OracleDataSource.getPhysicalConnection(OracleDataSource.java:280) <br/>at oracle.jdbc.xa.client.OracleXADataSource.getPooledConnection(OracleXADataSource.java:482) <br/>at oracle.jdbc.xa.client.OracleXADataSource.getXAConnection(OracleXADataSource.java:156) <br/>at oracle.jdbc.xa.client.OracleXADataSource.getXAConnection(OracleXADataSource.java:130) <br/>at org.jboss.jca.adapters.jdbc.xa.XAManagedConnectionFactory.getXAManagedConnection(XAManagedConnectionFactory.java:508) <br/>... 160 more
> </dadosTecnicos>
> <mensagens>
> <texto>
> Não foi possível finalizar a operação. Uma mensagem automática foi enviada para a área técnica responsável. Caso o problema persista, entre em contato com a Central de Serviços de TI (0800-644-1500) e informe a(s) sigla(s): SEGURANCA_053615. O atendente fará o encaminhamento e/ou priorização de sua manifestação.
> </texto>
> </mensagens>
> <reasonPhrase>Internal Server Error</reasonPhrase>
> <siglaErro>SEGURANCA_053615</siglaErro>
> <statusCode>500</statusCode>
> <url>
> /mapa-da-saude/rest/estabelecimentos/latitude/-3.0096295/longitude/-59.9881472/raio/7.0quantidade=30
> </url>
> </erroInfo>

**Comment by nmschumacher** [comment]
Prezado @weslleyng,

possivelmente o servidor estava fora do ar no momento desta requisição. Eu abri o [link enviado](http://mobile-aceite.tcu.gov.br/mapa-da-saude/rest/estabelecimentos/latitude/-3.0096295/longitude/-59.9881472/raio/7.0?quantidade=30) e o resultado retornou corretamente.

Algumas vezes, principalmente à noite ou durante o fim de semana, pode ocorrer de o servidor ficar indisponível por alguns instantes por diversas causas e devido a outros sistemas que utilizam o mesmo ambiente corporativo. Aguardamos sua compreensão.

Caso o erro persista, solicitamos que verifique se a requisição funciona normalmente na [plataforma Swagger](http://mobile-aceite.tcu.gov.br/mapa-da-saude/swagger/index.html?url=/mapa-da-saude/v2/api-docs#!/estabelecimentos/recuperarEstabelecimentosPorLocalizacaoUsingGET), pois pode ser algum erro em sua própria aplicação.

Att.

Equipe do [Desafio de Aplicativos Cívicos](http://portal.tcu.gov.br/desafio-aplicativos-civicos/o-desafio/).
