### ISSUE TITLE
Erro - rest/tipos-postagens

### ISSUE THREAD

**Issue by estevamdf2** [AppCivicoPlataforma/AppCivico#62]
Prezados,
Tentei fazer hoje uma inserção de tipo de postagem com a seguinte estrutura
`
{
  "codAplicativo": 373,
  "codTipoObjetoDestino": 0,
  "codTipoPostagemPai": 0,
  "descricao": "consulta remédio",
  "textoFormatoJson": "Objetivo. Armazenar dados da consulta a determinado medicamento pelo principio ativo ou nome do produto."
}
`
Inseri o token do usuário 1993 e após clicar em Try it out. O Swagger retornou a seguinte mensagem

"Status code 404 - texto: 'Tipo de postagem não cadastrado: 0' "

@Jmuribeca

**Comment by SkiaBr23** [comment]
@estevamdf2,

O atributo "codTipoPostagemPai" define o tipo de postagem pai referente ao novo tipo de postagem a ser criado. Este tipo deve ser válido (cadastrado no metamodelo previamente).

Depois de uma [rápida busca](http://mobile-aceite.tcu.gov.br:80/appCivicoRS/rest/tipos-postagem/0) por um tipo de postagem com código 0, verifiquei que este tipo não está cadastrado. 

Logo, sua inserção de tipo de postagem tenta atribuir um valor inválido ao codTipoPostagemPai.

> { "codAplicativo": 373, "codTipoObjetoDestino": 0, **_"codTipoPostagemPai": 0,_** "descricao": "consulta remédio", "textoFormatoJson": "Objetivo. Armazenar dados da consulta a determinado medicamento pelo principio ativo ou nome do produto." } 

Se o valor '0' foi atribuído como um valor arbitrário, sugiro apenas omitir esse atributo na inserção, e o seu tipo de postagem não possuirá um tipo pai. Caso queria cadastrar com um tipo pai, primeiro você precisa cadastrar o mesmo.

Atenciosamente,

Equipe do [Desafio de Aplicativos Cívicos](http://portal.tcu.gov.br/desafio-aplicativos-civicos/o-desafio/).

**Comment by estevamdf2** [comment]
Ok. Muito obrigado pelo esclarecimento.
