### ISSUE TITLE
Objetivo uso metamodelo.

### ISSUE THREAD

**Issue by estevamdf2** [AppCivicoPlataforma/AppCivico#63]
Prezados,
Um dos principais objetivos desta API é obter dados dos usuários do aplicativo. Entendi.
Entretanto, há alumas lacunas, digo -,  dúvidas, a cerca da forma de como seria a autenticação. 

Segue:

- A autenticação seria única (com o meu token) toda vez que o aplicativo é acessa (via minhas credências)?

- Outra forma (dúvida também), seria uma autenticação de cada usuário do aplicativo (este teria que ter login na aplicação)? Caso está for uma possibilidade, digo, a real, estaria impactando no meu negócio. Correto?

Não é claro o texto disponível que trata desse assunto.
Peço, por gentileza, maiores esclarecimento sobre o referido assunto.

No aguardo.

**Comment by monilouise** [comment]
@estevamdf2 

As credenciais são por usuário do aplicativo.

Atenciosamente,
Equipe do Desafio de Aplicativos Cívicos

**Comment by estevamdf2** [comment]
Ok. Desde já agradeço pelo feedaback.
