### ISSUE TITLE
Obter o codigo de todas as escolas

### ISSUE THREAD

**Issue by fabio1079** [AppCivicoPlataforma/AppCivico#64]
Utilizando como base a url "http://mobile-aceite.tcu.gov.br/nossaEscolaRS/rest/escolas" para pegar os códigos das escolas, tendo como resultado um pouco mais de 20 escolas.

Gostaria de saber se há alguma paginação liitando o número de escolas por requisição.

Aproveitando, também gostaria de saber se há uma forma melhor de se obter apenas os nome e o código sem ter que pegar dados desnecessários na requisição citada acima.

**Comment by SkiaBr23** [comment]
@fabio1079,

Recomendo a leitura da [**documentação da API de Escolas**](https://github.com/AppCivicoPlataforma/AppCivico/blob/master/EscolasAPI.md) deste repositório e [**via Swagger**](http://mobile-aceite.tcu.gov.br/appCivicoRS/swagger/index.html?url=/nossaEscolaRS/v2/api-docs#!/escolas/recuperarEscolasPorMunicipioUsingGET) para o melhor entendimento dos _endpoints._

> Gostaria de saber se há alguma paginação limitando o número de escolas por requisição.

No [tópico da busca de escolas](https://github.com/AppCivicoPlataforma/AppCivico/blob/master/EscolasAPI.md#buscar-escolas), estão disponíveis todos os parâmetros que podem ser utilizados nessa requisição. Um deles é o __quantidadeDeItens__, que define o número de itens a serem mostrados na busca, e tem o valor padrão de 20 caso não seja especificado. Para buscas com mais resultados, você pode enviar esse parâmetro com um número superior a 20 ou utilizar o sistema de paginação com o parâmetro __pagina.__

> Também gostaria de saber se há uma forma melhor de se obter apenas os nome e o código sem ter que pegar dados desnecessários na requisição citada acima.

No mesmo [link](https://github.com/AppCivicoPlataforma/AppCivico/blob/master/EscolasAPI.md#buscar-escolas) fornecido na pergunta anterior, existe a informação sobre o parâmetro __campos__, que pode ser enviado como uma string **"codEscola,nome"** para que a requisição só retorne esses atributos.

Atenciosamente,

Equipe do [Desafio de Aplicativos Cívicos](http://portal.tcu.gov.br/desafio-aplicativos-civicos/o-desafio/).
