### ISSUE TITLE
Serviço de EXCLUSÃO de postagens

### ISSUE THREAD

**Issue by Bonissauro** [AppCivicoPlataforma/AppCivico#65]
Depois de "rebolar" um tanto para encontrar uma forma de encaixar meu modelo no metamodelo de vocês, percebo que seria útil um serviço de exclusão de postagens, não apenas esse já disponibilizado, em que se pode excluir uma postagem desde que não hajam postagens relacionadas a ele, mas um que excluísse uma postagem específica, todos os seus conteúdos e as postagens relacionadas a ela, também com seus conteúdos. Um serviço que fizesse tudo isso num processo atômico, realizando o "crime" numa única chamada.

Tem jeito?

**Comment by nmschumacher** [comment]
@Bonissauro,

Acreditamos que seja mais funcional implementar um serviço que exclui apenas uma postagem e seus conteúdos independente de haver ou não postagens relacionadas, pois excluir também as postagens relacionadas e seus conteúdos pode não ser de maior proveito para outros usuários. Caso ainda assim esta solução não lhe atenda, por favor nos informe.

Estamos desenvolvendo esta solução aqui proposta. Quando o serviço estiver disponível lhe avisaremos.

Att.

Equipe do [Desafio de Aplicativos Cívicos](http://portal.tcu.gov.br/desafio-aplicativos-civicos/o-desafio/).

**Comment by Bonissauro** [comment]
@nmschumacher Na verdade, discordo totalmente. Qual o sentido de se excluir uma determinada postagem e deixar "n" postagens órfãs? Imagine, no meu caso, onde tenho uma aplicação em que um usuário pode postar alguma coisa e os demais usuários podem avaliar essa postagem. Cada uma dessas avaliações é uma postagem relacionada à postagem inicial. Se o "dono" da postagem iniciar decidir excluí-la, não há sentido em manter as demais, concorda?

Claro, eu poderia percorrer as postagens filhas, deletá-las e só então deletar a "postagem-mãe", mas isso me exigiria uma serie de chamadas extra aos web-services para uma mesma operação. Isso, pra começar, inviabiliza que a operação seja atômica e depois, ocasionaria uma serie de chamadas desnecessárias ao serviço, com um péssimo tempo de resposta ao usuário.

**Comment by nmschumacher** [comment]
@Bonissauro,

Realmente, no caso de avaliações de uma postagem faz sentido sim. Mas pense, por exemplo, em redes sociais em que postagens podem ser feitas com diversos conteúdos e existe, digamos, a _postagem A_ relacionada a ela. Não é em todos os casos que a _postagem A_, ao ser excluída, fará com que as demais postagens que a referenciam se tornem sem significado, inutilizáveis.

Outra problemática é o fato de que postagens que possuem postagem relacionada também podem ser  postagens referenciadas por alguma outra. No caso de uma exclusão em lote indesejada levaria a uma perda, talvez irreversível, de informações.

De todo modo, iremos discutir a possibilidade de implementar este serviço e lhe informamos por esta _issue_.

**Comment by Bonissauro** [comment]
Bom, não tenho certeza se esse modelo serviria para ideia de compartilhamento, mas realmente depende de como o desenvolvedor desenhou a parada. Mudemos meu "discordo totalmente" para um mais conservador e político "concordo em parte". Kkkk!!!

No meu caso específico, a necessidade está mais ligada àquela situação em que uma postagem recebe zero ou mais comentários. Cada comentário, por ter sido inserido por pessoas diferentes se trata de uma postagem nova ligada à inicial. Nesse caso, excluir a postagem mãe tornaria as postagens de comentários subsequentes desnecessárias.

Pretendo disparar essa operação de modo assíncrono, por isso, o usuário até nem vai notar tanto a demora de resposta dos web services. Minha principal preocupação é a ATOMICIDADE da operação. 

Sugiro que, para agradar gregos e troianos, vocês implementem um parâmetro para, opcionalmente, ( por conta e risco do desenvolvedor, claro) o serviço se comporte de uma ou outra forma.

**Comment by SkiaBr23** [comment]
@Bonissauro,

Obrigado pela sugestão! Analisamos essa possibilidade de exclusão em _cascade_ de postagem e iremos implementar essa opção no **DELETE** atual de postagens. Aviso por aqui quando as alterações forem publicadas.

Atenciosamente,

Equipe do [Desafio de Aplicativos Cívicos](http://portal.tcu.gov.br/desafio-aplicativos-civicos/o-desafio/).

**Comment by Bonissauro** [comment]
Obrigado, @SkiaBr23 !

Fico no aguardo, para implementar isso antes da data de entrega da proposta.

**Comment by Bonissauro** [comment]
Apenas lembrando, @SkiaBr23 , excluir as postagens **e os seus conteúdos**, certo?

**Comment by SkiaBr23** [comment]
> Apenas lembrando, @SkiaBr23 , excluir as postagens e os seus conteúdos, certo?

Exato =).

**Comment by SkiaBr23** [comment]
@Bonissauro,

Alteramos o funcionamento da exclusão para remover em cascata todas as postagens filhas e seus conteúdos também. Poderia testar e retornar com feedback?

Atenciosamente,

Equipe do [Desafio de Aplicativos Cívicos](http://portal.tcu.gov.br/desafio-aplicativos-civicos/o-desafio/).

**Comment by Bonissauro** [comment]
@SkiaBr23 Dois detalhes:

1) de vez em quando, em uma ou outra chamada, recebo um erro 500 do servidor. Alguns segundos mais tarde, submeto novamente a mesma operação e funciona. O que pode estar causando essa intermitência?

2) quando mando deletar uma postagem com um código inexistente, não estou recebendo o 404, conforme documentado, mas apenas um 200, como se a postagem existisse e tivesse mesmo sido deletada.

**Comment by tallysmartins** [comment]
Acho que encontrei uma vulnerabilidade um tanto crítica... Vi aqui que um usuário pode excluir qualquer postagem do sistema. É possível que alguém faça um crawler e apague TODAS as postagens da base de TODOS os apps! Isso não deveria ser possível!

**Comment by SkiaBr23** [comment]
@tallysmartins,

Respondi esse problema na issue #67.

**Comment by SkiaBr23** [comment]
@Bonissauro,

> O que pode estar causando essa intermitência?
- O erro retornado é sempre 500 ou ocorrem outros erros (503 por exemplo) ? Poderia enviar a _stacktrace_ de um deles para analisarmos?

> quando mando deletar uma postagem com um código inexistente, não estou recebendo o 404
- Já corrigimos esse problema e publicamos as alterações. Agora uma requisição de exclusão de postagem inexistente retornará erro 404 (Postagem não encontrada)

Atenciosamente,

Equipe do [Desafio de Aplicativos Cívicos](http://portal.tcu.gov.br/desafio-aplicativos-civicos/o-desafio/).

**Comment by Bonissauro** [comment]
"_O erro retornado é sempre 500?_"
R. Sim, era. Digo "era" porque parou de acontecer. Pelo menos comigo.

"_Já corrigimos esse problema._"
R. Já testei aqui e tá tudo certo!

**Comment by SkiaBr23** [comment]
@Bonissauro,

Suspeitamos que as falhas recorrentes em algumas horas do dia se devem ao alto número de requisições. Caso ocorra novamente, favor nos informar a _stacktrace_ completa para uma análise mais profunda, abrindo uma nova _issue_ relacionada à esse problema.

Atenciosamente,

Equipe do [Desafio de Aplicativos Cívicos](http://portal.tcu.gov.br/desafio-aplicativos-civicos/o-desafio/).
