### ISSUE TITLE
Possível problema na API de exclusão e reativação de usuário

### ISSUE THREAD

**Issue by agnoldo** [AppCivicoPlataforma/AppCivico#66]
Boa tarde,

Cadastrei uma pessoa (2081) na plataforma usando apenas token Facebook, sem senha. Em seguida, exclui o cadastro usando o Swagger. Até aí tudo bem. Finalmente tentei reativar a pessoa também usando o Swagger e obtive erro 404 (Usuário inválido) ao fornecer appIdentifier, email e token do Facebook. Ao fornecer senha (tentei também reativar agora com senha), obtive erro 500.

Alguma opinião a respeito?

Obrigado,

Arnaldo

**Comment by nmschumacher** [comment]
@agnoldo,

A documentação do Swagger será atualizada, mas por [este link do Git](https://github.com/AppCivicoPlataforma/AppCivico/blob/master/MetamodeloAPI.md#reativar-cadastro) está documentado que o e-mail e a senha devem ser utilizados em conjunto. Para os demais casos, basta informar apenas o token, sem o e-mail.

Acrescentei uma obsevação no Git para ficar mais clara a correta utilização da reativação de cadastro.

O erro 404 pode ter ocorrido porque o _appIdentifier_ ou o _facebookToken_ utilizado foi incorreto. Realizei uma busca sobre o usuário de código 2081 e percebi que o tipo de perfil dele pertence ao aplicativo 351, por isso é inferido que o cadastro seja deste aplicativo. Pode ser que você esteja utilizando o tipo de perfil de um aplicativo para cadastrar usuários em outro aplicativo. Neste caso, o cadastro não será encontrado.

Sobre o outro erro, você tentou reativar este mesmo usuário (2081) informando a senha? Se sim, de fato o erro ocorre porque o cadastro dele foi feito, como você disse, sem a senha.

Caso tenha mais dúvidas e para mais esclarecimentos, por favor nos informe.

Att.

Equipe do [Desafio de Aplicativos Cívicos](http://portal.tcu.gov.br/desafio-aplicativos-civicos/o-desafio/).
