### ISSUE TITLE
Dúvida: Login com Token Externo

### ISSUE THREAD

**Issue by tallysmartins** [AppCivicoPlataforma/AppCivico#68]
Cenário:

Usuário loga na minha aplicação com Facebook e eu tenho acesso a seu email e FBToken
Eu crio uma conta no MetaModelo com este email e o token devolvido pelo Facebook.
O token do facebook expira e o token da núvem cívica também (7 dias)

Então eu perdi o acesso a conta? Vou ter que resetar a senha do usuário e levá-lo para uma tela de recuperação da conta?

Ao meu ver deveria ter um endpoint para que fosse utilizado como callback de um login com API externas. Então, o servidor da nuvem deveria ser responsável por identificar o usuário, validar o token com a aplicação externa e atualizá-lo no cadastro do usuário.

**Comment by SkiaBr23** [comment]
@tallysmartins,

O metamodelo não possui nenhuma conexão com API's externas como o Facebook. Dispomos dos campos do usuário para armazenar os tokens e autenticação por meio dessa informação, porém a atualização desses tokens fica na responsabilidade do desenvolvedor. 

De acordo com a documentação do Facebook sobre seus tokens,

> Os aplicativos móveis nativos que usarem SDKs do Facebook terão tokens de acesso de vida longa, válidos por até 60 dias. Esses tokens serão atualizados uma vez ao dia quando a pessoa que usar seu aplicativo fizer uma solicitação aos servidores do Facebook. Se nenhuma solicitação for feita, o token expirará depois de 60 dias, e a pessoa terá que passar pelo fluxo de login novamente para obter um novo token.

Caso ainda ocorra de 60 dias se passarem sem nenhuma requisição com esse token, o mesmo será expirado e deve ser atualizado tanto na API do Facebook como na nuvem cívica (que não possui expiração de token do Facebook). Para resolver esse problema, alguns desenvolvedores armazenam a informação de email+token do usuário localmente no dispositivo, e caso o token do Facebook necessite ser atualizado, ainda estarão presentes as credenciais da nuvem cívica para que seja utilizado o [_endpoint_ de atualização de tokens](http://mobile-aceite.tcu.gov.br/appCivicoRS/swagger/index.html?url=/appCivicoRS/v2/api-docs#!/pessoas/atualizarTokensUsingPUT).

Sobre o token da nuvem cívica, é recomendado que seja atualizado ([via _endpoint_ de autenticação](http://mobile-aceite.tcu.gov.br/appCivicoRS/swagger/index.html?url=/appCivicoRS/v2/api-docs#!/pessoas/autenticarUsingGET)) a cada inicialização da sua aplicação.

Atenciosamente,

Equipe do [Desafio de Aplicativos Cívicos](http://portal.tcu.gov.br/desafio-aplicativos-civicos/o-desafio/).

**Comment by tallysmartins** [comment]
Então qual a razão para armazenar tokens de API's externas na nuvem cívica?

Att

**Comment by SkiaBr23** [comment]
@tallysmartins,

O armazenamento do token de API's externas na nuvem cívica tem como objetivo disponibilizar a autenticação do usuário na nuvem cívica (necessária para executar várias requisições) não só por meio de email + senha cadastrados, mas também por token externo, evitando que o usuário precise informar esses dados.

Caso este funcionamento não se adeque à sua aplicação, o cadastro/autenticação na nuvem cívica sempre pode ser feito também via email + senha.

Atenciosamente,

Equipe do [Desafio de Aplicativos Cívicos](http://portal.tcu.gov.br/desafio-aplicativos-civicos/o-desafio/).

**Comment by AleBarreto** [comment]
Erro ao cadastrar usuário com Token do Google.

{
  "url": "/appCivicoRS/rest/pessoas",
  "statusCode": 400,
  "reasonPhrase": "Bad Request",
  "mensagens": [
    {
      "texto": "googleToken deve ter no máximo 255 caracteres"
    }
  ]
}

**Comment by SkiaBr23** [comment]
@AleBarreto,

Já aumentamos os campos de token para suportar até **3000 caracteres**. Porém, estamos resolvendo um pequeno problema técnico e logo que possível publicaremos a alteração. Aviso por aqui quando estiver disponível.

Caso uma _issue_ já estiver fechada, sugerimos a criação de uma nova _issue_ para que possamos acompanhar de forma mais organizada e objetiva.

Atenciosamente,

Equipe do [Desafio de Aplicativos Cívicos](http://portal.tcu.gov.br/desafio-aplicativos-civicos/o-desafio/).

**Comment by SkiaBr23** [comment]
@AleBarreto,

As alterações foram publicadas. Os campos agora já devem estar funcionando para tokens até 3000 caracteres.

Atenciosamente,

Equipe do [Desafio de Aplicativos Cívicos](http://portal.tcu.gov.br/desafio-aplicativos-civicos/o-desafio/).

**Comment by JuanBarros2** [comment]
Tive problema ao tentar autenticar com o facebook. Enviei o token do facebook e o email no Swagger e recebo o código 401 na resposta. Se eu uso o serviço de recuperar senha e faço a requisição com a senha + email +tokenfacebook ele me retorna a autenticação. Outra questão é que quando eu ponho o appIdentifier, ele não funciona (em nenhum caso). Aguardo respostas

**Comment by AleBarreto** [comment]
@JuanBarros2 acontece a mesma coisa comigo, Cadastrar ele cadastra normal porem autenticar retorna código 401.

**Comment by SkiaBr23** [comment]
@JuanBarros2 e @AleBarreto,

Recomendo que evitem a discussão em issues já fechadas, visto que fica mais difícil de acompanhar novas postagens e de organizar os problemas, o que atrasa a resposta e prejudica os desenvolvedores. Da próxima vez, sugiro abrir uma nova _issue_ =D

> Se eu uso o serviço de recuperar senha e faço a requisição com a senha + email +tokenfacebook ele me retorna a autenticação.

A autenticação é feita por senha OU por token. Se os dois campos forem enviados, o sistema irá autenticar pela senha. 

> Enviei o token do facebook e o email no Swagger e recebo o código 401 na resposta

O código 401 (Unauthorized) pode estar sendo retornado pelo fato do token passado ser diferente do token cadastrado. Tem certeza que está enviando o mesmo token na autenticação? A API do Facebook renova o token automaticamente porém a autenticação deve ser feita com o token que foi cadastrado e está presente na base de dados do Metamodelo.

> Outra questão é que quando eu ponho o appIdentifier, ele não funciona (em nenhum caso)

A autenticação com o appIdentifier só funciona caso o usuário em questão tenha um perfil cadastrado nesse aplicativo. Sugiro [verificar na documentação.](https://github.com/AppCivicoPlataforma/AppCivico/blob/master/MetamodeloAPI.md#cadastrar-perfil)

Atenciosamente,

Equipe do [Desafio de Aplicativos Cívicos](http://portal.tcu.gov.br/desafio-aplicativos-civicos/o-desafio/).

**Comment by JuanBarros2** [comment]
Testei agora e realmente, o facebook atualizou o token. Isso quer dizer que uma vez que eu perca o facebooktoken da memória do meu celular não terei mais acesso ao serviço para aquele usuário? Só enviando uma solicitação de recuperação de senha? 
PS.: Desculpa pela bagunça na issue. Achei que estava dentro do tema.

**Comment by monilouise** [comment]
@JuanBarros2 

Existe uma operação específica para atualização de tokens:

http://mobile-aceite.tcu.gov.br/appCivicoRS/swagger/index.html?url=/appCivicoRS/v2/api-docs#!/pessoas/atualizarTokensUsingPUT
