### ISSUE TITLE
Sem acesso a página para inscrição da proposta

### ISSUE THREAD

**Issue by raphaelporto** [AppCivicoPlataforma/AppCivico#69]
Ao acessar o portal https://contas.tcu.gov.br/ead/ e clicar no banner do concurso, sou redirecionado para a tela de login. Mesmo fazendo login novamente, não consigo acesso a página do curso do concurso https://contas.tcu.gov.br/ead/course/view.php?id=413.

Att.,

**Comment by SkiaBr23** [comment]
@raphaelporto,

Você efetuou o cadastro no [portal do TCU](http://portal.tcu.gov.br/)? Se sim, certifique-se que está logado e utilizando as credenciais corretas para acessar o moodle em https://contas.tcu.gov.br/ead/course/view.php?id=413. Nesta página, você deve clicar no botão "Inscreva-me" para ter acesso ao Moodle do Desafio.

Testei o acesso à pagina de envio dos arquivos dos aplicativos e está funcionando normalmente, porém já notificamos os responsáveis pelo moodle do Desafio e logo que tivermos alguma resposta sobre esse problema, aviso por aqui.

Atenciosamente,

Equipe do [Desafio de Aplicativos Cívicos](http://portal.tcu.gov.br/desafio-aplicativos-civicos/o-desafio/).
