### ISSUE TITLE
EscolasAPI - GetEscolas - Filtro geográfico não funciona

### ISSUE THREAD

**Issue by jardelnovaes** [AppCivicoPlataforma/AppCivico#7]
Olá, não sei se estou utilizando de forma errada ou se realmente não está funcionando, mas ao tentar consultar escolas em determinada posição geográfica é retornado as **20 primeiras escolas de Rondônia**, usando o formato abaixo:
http://mobile-aceite.tcu.gov.br:80/nossaEscolaRS/rest/escolas/latitude/-48.83010864/longitude/-26.30326424/raio/10

Também tentei usando o formato que é informado em *_EstabelecimentosAPI *_(GET - /rest/estabelecimentos/latitude/{latitude}/longitude/{longitude}/raio/{raio})
http://mobile-aceite.tcu.gov.br:80/nossaEscolaRS/rest/escolas?latitude=-48.83010864&longitude=-26.30326424&raio=10

Neste caso nada é retornado (acredito que essa rota não exista em EscolasAPI)

Sendo assim gentilmente peço:

**1) Que informem como usar a API filtrando por posição geográfica, no caso de eu estar usando de forma errada.
2) Que seja corrigido a EscolasAPI, caso seja um BUG.**

_Abrirei outro Issue para solicitar a implementação de filtro por UF/Cidade._

Grato,
Jardel Novaes

**Comment by SkiaBr23** [comment]
Olá @jardelnovaes,
Para a busca geográfica, o modelo correto é o seguinte:

**(GET)**  /rest/escolas/latitude/{latitude}/longitude/{longitude}/raio/{raio}

Que é o padrão para requisições com parâmetros **obrigatórios**. Caso seja usado o modelo de parâmetro opcional (latitude=xxx&longitude=yyy&raio=zzz), o endpoint não entende a informação e acaba enviando as primeiras entradas do banco como resposta. Recomendo sempre checar a documentação via Swagger para confirmar o formato da URL de cada endpoint.

Com o seu exemplo, um ponto geográfico que se encontra no meio do Oceano Atlântico, a busca realmente tem que retornar '_no content_'. Acredito que você tenha **invertido latitude com longitude** nessa busca (pois se os valores forem invertidos, o ponto é próximo a Joinville-SC).

No momento, a documentação do EscolasAPI não explica isso claramente, mas já solicitei ao Luciano a atualização. 

Rafael

**Comment by jardelnovaes** [comment]
Certo, no formato (GET) /rest/escolas/latitude/{latitude}/longitude/{longitude}/raio/{raio} realmente estava invertendo os parâmetros.

Grato pela atenção.

**Comment by joaopaulopereira** [comment]
Olá @SkiaBr23 . Gostaria de saber se eu posso internalizar e trabalhar esses dados ou outros também abertos (de outros portais do governo), de forma a trata-los em um banco separado, e só então serem consumidos pelo aplicativo sem prejuízo de quebrar alguma regra do concurso?

**Comment by AppCivicoPlataforma** [comment]
Olá @joaopaulopereira,

Este canal deve ser usado exclusivamente para dúvidas técnicas, correções de erro e melhorias na API. 

Dúvidas acerca das regras do [concurso ](http://portal.tcu.gov.br/desafio-aplicativos-civicos/o-desafio/) devem ser encaminhadas ao e-mail concursoaplicativos@tcu.gov.br.
