### ISSUE TITLE
Desempenho da Nuvem Cívica

### ISSUE THREAD

**Issue by brunomarquete** [AppCivicoPlataforma/AppCivico#74]
Bom dia,

O aplicativo que desenvolvemos para o desafio de aplicativos cívicos (Mapa Escolar) por vezes apresenta baixo desempenho nas consultas aos endpoints da Nuvem Cívica. Algumas vezes algumas consultas demoram cerca 30s ou mais. Um exemplo é a timeline de postagens que muitas das vezes apresenta elevado tempo de retorno de resposta. Isso tem nos preocupado já que estamos divulgando nosso aplicativo e o número de usuários tem aumentado. Seria interessante um adequado desempenho para garantir a melhor usabilidade. Vocês conseguem diagnosticar se o ocorrido é questão de infraestrutura ou outros fatores adversos? Há possibilidades de ajustes para que o desempenho do backend seja melhor? 

Atenciosamente,

**Comment by AppCivicoPlataforma** [comment]
@brunomarquete,

Nos dias que antecederam a entrega dos aplicativos houve pico de acessos à nuvem cívica e, consequentemente, degradação do desempenho. Por vezes, ocorreu inclusive momentos de indisponibilidade (reportados em outras _issues_).

Vencida a entrega dos aplicativos, iniciaremos [trabalhos de evolução da API do metamodelo](https://github.com/AppCivicoPlataforma/AppCivico/projects/1) e para robustecer a plataforma. 

Receba os parabéns pelo produto entregue (Mapa Escolar). Esperamos manter contato direto para melhorarmos cada vez mais nossa plataforma.

Atenciosamente,

Equipe do [Desafio de Aplicativos Cívicos](http://portal.tcu.gov.br/desafio-aplicativos-civicos/o-desafio/).

**Comment by brunomarquete** [comment]
@AppCivicoPlataforma, muito obrigado pelo retorno e pelo trabalho realizado. 

Atenciosamente,
