### ISSUE TITLE
Publicação do resultado

### ISSUE THREAD

**Issue by matbrandao** [AppCivicoPlataforma/AppCivico#75]
Vocês possuem alguma atualização sobre a publicação do resultado? 
Na página do desafio diz que o mesmo deveria ter sido divulgado ontem dia 22/11.

**Comment by julianesansil** [comment]
Vi que o cronograma foi retificado.
http://pesquisa.in.gov.br/imprensa/jsp/visualiza/index.jsp?jornal=3&pagina=157&data=23/11/2016

**Comment by AppCivicoPlataforma** [comment]
Obrigado pela contribuição @julianesansil. Ademais, também foi atualizada a página do [Desafio de Aplicativos Cívicos](http://portal.tcu.gov.br/desafio-aplicativos-civicos/) com as novas datas.

Atenciosamente,

Equipe do [Desafio de Aplicativos Cívicos](http://portal.tcu.gov.br/desafio-aplicativos-civicos/o-desafio/).
