### ISSUE TITLE
Atualizações após a data de inscrição.

### ISSUE THREAD

**Issue by matbrandao** [AppCivicoPlataforma/AppCivico#77]
É permitido efetuar atualizações para concertar pequenos erros, após a data final de inscrição? Ou seja, após o dia 15/11. 

Vi alguns apps do desafio fazendo isso, mas não encontrei nada falando sobre se isso é permitido ou não.

**Comment by AppCivicoPlataforma** [comment]
@matbrandao,

As versões utilizadas para avaliação no concurso já foram baixadas e instaladas em dispositivos do [TCU](http://portal.tcu.gov.br/inicio/index.htm). Não há problema em corrigir pequenos erros. Muito pelo contrário, trata-se de comportamento a ser incentivado.

Atenciosamente,

Equipe do [Desafio de Aplicativos Cívicos](http://portal.tcu.gov.br/desafio-aplicativos-civicos/o-desafio/).
