### ISSUE TITLE
Detalhamento da nota do resultado final

### ISSUE THREAD

**Issue by jessehaniel** [AppCivicoPlataforma/AppCivico#78]
Vi que o resultado foi publicado hoje a tarde http://portal.tcu.gov.br/desafio-aplicativos-civicos/noticias/resultado-final-do-desafio-de-aplicativos-civicos-controle-social-digital-2016.htm

Gostaria de saber como proceder para ter acesso detalhado às notas da avaliação.

**Comment by bryanollivie** [comment]
Gostaria de saber qual foi o processo de teste utilizado para classificação ?

**Comment by AppCivicoPlataforma** [comment]
Olá @jessehaniel e @bryanollivie ,

Este canal deve ser usado exclusivamente para dúvidas técnicas, correções de erro e melhorias na API.

Dúvidas acerca das regras do concurso devem ser encaminhadas ao e-mail concursoaplicativos@tcu.gov.br.

Atenciosamente,

Equipe do [Desafio de Aplicativos Cívicos](http://portal.tcu.gov.br/desafio-aplicativos-civicos/o-desafio/).
