### ISSUE TITLE
EscolasAPI - GetEscolas - Filtro adicionar filtro por UF/Município

### ISSUE THREAD

**Issue by jardelnovaes** [AppCivicoPlataforma/AppCivico#8]
Olá, 

Gostaria de saber se existe a possibilidade de adicionar filtro por **UF e Município** em getEscolas da EscolasAPI.

Caso necessário posso ser um desenvolvedor colaborador, seja em .NET, Java, PHP  entre outras tecnologias que conheço.

**Comment by nmschumacher** [comment]
Prezado @jardelnovaes,

Na issue #4 também foi solicitado o filtro por UF e ele foi implementado. O filtro por município já estava disponível. Portanto, agora é possível buscar escolas de acordo com os parâmetros municipio, uf, situacaoFuncionamento e categoriaEscolaPrivada.

Obrigado pela colaboração!

**Comment by jardelnovaes** [comment]
Já atende minha necessidade, obrigado.
