### ISSUE TITLE
Duvida

### ISSUE THREAD

**Issue by andersonlfurlan** [AppCivicoPlataforma/AppCivico#80]
Boa tarde,
os endpoints em questao podem ser utilizados em trabalhos academicos

**Comment by AppCivicoPlataforma** [comment]
Olá @alsfurlan ,

> os endpoints em questao podem ser utilizados em trabalhos academicos
Sem dúvida! A nuvem cívica é de livre uso para qualquer aplicativo cívico.

Pedimos desculpas pela loooooonga demora na resposta. Ocorre que a nuvem cívica passou por um processo de reestruturação e revisão e apenas neste segundo semestre os rumos foram novamente estabelecidos.

[]´s

**Comment by andersonlfurlan** [comment]
Obrigado :). Sem problemas! Então, no caso, os endpoints estão ok e podem ser utilizados para trabalhos? Desde já agradeço.
