### ISSUE TITLE
Disponibilização de bases abertas pelo TCU

### ISSUE THREAD

**Issue by caduvieira** [AppCivicoPlataforma/AppCivico#82]
Teria como o TCU disponibilizar bases como:
[ ] Base completas de políticos por mandato
[ ] Parentes de políticos para combate ao nepotismo
[ ] Bases das empresas conforme decreto 8777/2016

**Comment by SkiaBr23** [comment]
@silvablack,

Por enquanto a nuvem cívica tem acesso apenas às bases de dados especificadas na documentação.

Obrigado pela sugestão! Caso sejam disponibilizadas informações dessa categoria futuramente, avisaremos por aqui.
