### ISSUE TITLE
Estabelecimentos Saúde - LEITOS

### ISSUE THREAD

**Issue by silvablack** [AppCivicoPlataforma/AppCivico#83]
Boa tarde srs.

Teria como disponibilizar um acesso as informações de leitos das unidades de saúde?

**Comment by SkiaBr23** [comment]
@silvablack,

Por enquanto a nuvem cívica tem acesso apenas às bases de dados especificadas na documentação. 

Obrigado pela sugestão! Caso sejam disponibilizadas informações de leitos futuramente, avisaremos por aqui.
