### ISSUE TITLE
Ajuda - Dados IDEB

### ISSUE THREAD

**Issue by thlucena** [AppCivicoPlataforma/AppCivico#84]
Olá, sou estudante da área de tecnologia da informação e estive pesquisando APIs na área de educação, quando me deparei com o projeto AppCivico.

Percebi que através da API de escolas é possível obter dados sobre os índices do IDEB por escola. Gostaria de saber qual a **fonte dos dados do IDEB** que vocês desenvolvedores do projeto utilizaram para alimentar a API. Estou precisando dos **dados do IDEB por escola atualizados** para um projeto da graduação e realmente já pesquisei por muitos sites do INEP e não consigo tais dados para download. 

Agradeço desde já pela atenção.

**Comment by SkiaBr23** [comment]
Olá @thiagocesarm, 

As informações do Censo Escolar são providas pelo [Instituto Nacional de Estudos e Pesquisas Educacionais Anísio Teixeira (INEP)](http://portal.inep.gov.br/). Nossa equipe expõe os dados desta base por meio de Web Services.

Possivelmente os dados que você está buscando são aqueles disponibilizados no [site de Dados Abertos do Governo Federal](http://dados.gov.br/), mais especificamente na [busca por dados do IDEB](http://dados.gov.br/dataset?q=ideb).

Atenciosamente,

**Equipe da Nuvem Cívica**
