### ISSUE TITLE
Cadastro inviabilizado

### ISSUE THREAD

**Issue by GabrielDViana** [AppCivicoPlataforma/AppCivico#85]
Na tentantiva de cadastro de nova aplicação para desenvolvedores, o site redireciona para o login

**Comment by SkiaBr23** [comment]
@GabrielDViana,

Obrigado por informar o erro. Estamos analisando o problema no Portal e em breve mando por aqui quaisquer atualizações.

Enquanto isso, para não prejudicar o desenvolvimento, sugiro que as ações que seriam feitas via Portal sejam feitas por meio da [interface do Swagger](http://mobile-aceite.tcu.gov.br/appCivicoRS/swagger/index.html?url=/appCivicoRS/v2/api-docs). Fizemos vários testes aqui e por lá tudo funciona normalmente.

**Comment by SkiaBr23** [comment]
@GabrielDViana qual navegador você está utilizando? Verificamos que o Google Chrome a partir da versão 61.0.3163.100 está tendo problemas relacionados à cookies e sessões de usuário. Algumas máquinas daqui com versões anteriores conseguem efetuar o cadastro normalmente, assim como em outros navegadores.

Poderia testar com outro navegador e mandar feedback? Aguardo resposta.

**Comment by SkiaBr23** [comment]
Fechando a issue por falta de resposta. Caso seja necessária uma discussão futura sobre o tema, favor reabrir a issue.

[]'s
