### ISSUE TITLE
Dúvidas sobre a autenticação de usuário.

### ISSUE THREAD

**Issue by AllanNobre** [AppCivicoPlataforma/AppCivico#87]
Após ler a documentação e fazer alguns testes sobre autenticação do usuário, surgiram algumas dúvidas:

**Dúvida 1**
* Ao autenticar um usuário usando "GET - /rest/pessoas/autenticar" existe o campo "appIdentifier", para caso a autenticação exija que a pessoa possua um perfil no aplicativo, mas para que ela seja associada a um perfil no aplicativo, ela tem que estar autenticada, logo quando tento autenticar um usuário cadastrado que terá um perfil, e adiciono esse valor "appIdentifier" a requisição no próprio swagger, ele me retorna o erro abaixo, contudo quando tiro o "appIdentifier" ele autentica o usuário normalmente e só então com o token recebido eu posso associá-lo a um perfil, dessa forma, com o perfil associado, quando tento autenticá-lo novamente, ele aceita a requisição com o "appIdentifier" sem o erro abaixo, contudo aceitando ser autenticado sem o valor do "appIdentifier" também.
Logo, qual a necessidade do "appIdentifier" na autenticação do usuário?!
```
{
  "url": "/appCivicoRS/rest/pessoas/autenticar",
  "statusCode": 401,
  "reasonPhrase": "Unauthorized",
  "mensagens": [
    {
      "texto": "Falha na autenticação"
    }
  ],
  "mensagensComoArray": [
    {
      "texto": "Falha na autenticação"
    }
  ]
}
```

**Dúvida 2**
* Ao autenticar um usuário usando "GET - /rest/pessoas/autenticar" eu recebo o token que vale por 7 dias, no entanto, eu não encontrei uma requisição que me permita recuperar esse token, ela existe? Caso não, tem alguma sugestão para manipular esse token?

**Dúvida 3**
* Ao utilizar a requisição "PUT - /rest/pessoas/{codPessoa}/definirNovoToken" o que acontece com o Token de usuário, já que eu não consigo pegá-lo novamente, somente gerá-lo, nesta requisição ele revalida o token por mais sete dias?

**Dúvida 4**
* Um usuário autenticado na nuvem pode ter vários tokens? Ao autenticá-lo diversas vezes com a requisição "GET - /rest/pessoas/autenticar", ele terá vários tokens correspondentes ou o token anterior será substituído?

**Comment by SkiaBr23** [comment]
Olá @AllanNobre! 

Respondendo as dúvidas:

#### 1. De acordo com a [documentação da requisição](https://github.com/AppCivicoPlataforma/AppCivico/blob/master/MetamodeloAPI.md#autenticar) de autenticação, 

> **appIdentifier**: Parâmetro de header. ***Opcional***. Código do app, caso a autenticação exija que a pessoa possua um perfil no aplicativo.

Caso seu aplicativo execute uma operação que toma como premissa que o usuário tenha um perfil no aplicativo, essa premissa pode ser testada enviando o ***appIdentifier***, retornando uma falha caso o usuário não tenha perfil no aplicativo mesmo com as credenciais corretas. Esse parâmetro é útil pois o cadastro de pessoas na nuvem cívica é global, servindo para outras aplicações que também utilizem a nuvem. Dessa forma a presença deste usuário na sua base pode ser testada com esse parâmetro. Porém, é um parâmetro opcional, justificando o funcionamento normal da autenticação sem este parâmetro.

#### 2. Sobre o armazenamento do token:
> eu recebo o token que vale por 7 dias, no entanto, eu não encontrei uma requisição que me permita recuperar esse token, ela existe? 

Não é possível recuperar o último token validado pois isso acarretaria em uma nova requisição com credenciais, que a própria autenticação já faz. 

> Caso não, tem alguma sugestão para manipular esse token?

O armazenamento do token recebido na autenticação fica em cargo da sua aplicação, podendo ser guardado localmente no dispositivo (ex: SharedPreferences em aplicações Android), no cache da aplicação ou de qualquer outra forma que vocês preferirem.

#### 3. Sobre a requisição DefinirNovoToken:

> Ao utilizar a requisição "PUT - /rest/pessoas/{codPessoa}/definirNovoToken" o que acontece com o Token de usuário, já que eu não consigo pegá-lo novamente, somente gerá-lo, nesta requisição ele revalida o token por mais sete dias?

De acordo com a [documentação da requisição](https://github.com/AppCivicoPlataforma/AppCivico/blob/master/MetamodeloAPI.md#alterar-token):

> Altera os dados de token de ***rede social*** do usuário. Pelo menos um token deve ser passado via header para atualização.

Essa requisição tem como finalidade atualizar algum atributo de token de rede social do usuário, não estando relacionado ao token de autenticação da nuvem cívica. O token de autenticação não pode ser revalidado por mais 7 dias, apenas trocado por um mais novo via /autenticar.

#### 4. Ao autenticar novamente o usuário, o token anterior NÃO torna-se inválido, podendo ser utilizado da mesma forma que o novo token passado, ainda com 7 dias de validade.

Continue mandando as dúvidas por aqui. Tentarei responder assim que possível!

[]'s

**Comment by SkiaBr23** [comment]
#### EDIT: Ajuste na resposta da dúvida 4.

**Comment by AllanNobre** [comment]
Ok, muito obrigado pelas respostas, @SkiaBr23 . Ajudou bastante.
