### ISSUE TITLE
Problema com o link, /rest/pessoas/{codPessoa}/perfil GET, POST, PUT, DEL.

### ISSUE THREAD

**Issue by joao4018** [AppCivicoPlataforma/AppCivico#89]
As funcionalidades no swagger estão retornando 200 quando executamos uma operação em qualquer um dos métodos, mas ao acessar o link que nos fornece um JSON com o perfil recebemos um erro 400.
http://mobile-aceite.tcu.gov.br:80/appCivicoRS/rest/pessoas/5676/perfil.

**Comment by SkiaBr23** [comment]
@joao4018,

A requisição de busca de perfil via código de usuário que você está utilizando precisa da informação do código do aplicativo enviada pelo _header_. O erro **_"The request sent by the client was syntactically incorrect."_** é mostrado visto que não foi encontrado o parâmetro obrigatório no _header._ A [documentação desse endpoint](https://github.com/AppCivicoPlataforma/AppCivico/blob/master/MetamodeloAPI.md#buscar-perfil) explica um pouco melhor.

[]'s
