### ISSUE TITLE
Filtro por munícipio na API de Estabelecimentos

### ISSUE THREAD

**Issue by ragulhari** [AppCivicoPlataforma/AppCivico#9]
Bom dia,

Gostaria de verificar a possibilidade de se adicionar ao recurso "Estabelecimentos" da API um filtro por município e UF, hoje o único filtro disponível relativo à localização é a posição latitude/longitude.

Desde já agradeço.

**Comment by SkiaBr23** [comment]
Olá @ragulhari,

Foi adicionado um GET de busca por parâmetros opcionais no contexto Estabelecimentos, que funciona da mesma maneira que as buscas do contexto de Assistência Social. Recomendo verificar a documentação e testar via [Swagger](http://mobile-aceite.tcu.gov.br/appCivicoRS/swagger/index.html?url=/mapa-da-saude/v2/api-docs#!/estabelecimentos/recuperarEstabelecimentosUsingGET). 

**Exemplo de busca:**

[http://mobile-aceite.tcu.gov.br:80/mapa-da-saude/rest/estabelecimentos?municipio=brasilia&uf=df&quantidade=30](http://mobile-aceite.tcu.gov.br:80/mapa-da-saude/rest/estabelecimentos?municipio=brasilia&uf=df&quantidade=30)

Obrigado pela sugestão.

**Comment by ragulhari** [comment]
@SkiaBr23 vou analisar com calma mais tarde, mas obrigado pelo retorno!

Fiz um teste rápido agora e percebi uma coisa estranha, não sei se seria a regra na API ou nos dados, mas o campo "temDialise" tem retornado "Sim" em todos os estabelecimentos, mesmo os que eu sei que não tem aqui na minha cidade (Bauru/SP). Estou apenas reportando porque me parece um bug, mas não tenho certeza.

Abraço, Ricardo

**Comment by monilouise** [comment]
Olá @ragulhari ,

Exemplos de estabelecimentos que retornam "Não" na informação referente a diálise:

http://mobile-aceite.tcu.gov.br:80/mapa-da-saude/rest/estabelecimentos/unidade/3530602072912
http://mobile-aceite.tcu.gov.br:80/mapa-da-saude/rest/estabelecimentos/unidade/3528405303575

Ou seja, não se trata de problema na API.  Os dados utilizados são provenientes de outras bases públicas (ex.: dados disponibilizados pelo Ministério da Saúde), podendo portanto apresentarem problemas na origem.

**Comment by ragulhari** [comment]
Ok, testei a API, aparentemente tudo certo. Fechando a issue, muito obrigado!
