### ISSUE TITLE
Desativar conselheiros da Aplicação através do perfil

### ISSUE THREAD

**Issue by AllanNobre** [AppCivicoPlataforma/AppCivico#90]
### Funcionalidade Requisitada
Estou abrindo essa _Issue_ pra deixar registrado o pedido da funcionalidade que diz respeito às permissões de associação, **desassociação** e **alteração de perfil** serem restritas ao usuário em questão **OU** à credencial do responsável pelo aplicativo, sendo possível a utilização de um "_token_ geral da aplicação" para que essas ações sejam tomadas por um usuário com permissões mais elevadas. @SkiaBr23 , existe alguma previsão de quando estará pronta essa funcionalidade, se for possível implementa-la?

#### Desassociar Conselheiro
A issue do projeto correspondente a desassociação é a <a href="https://github.com/fga-gpp-mds/2017.2-MerendaMais/issues/73">US14 - Desativar conselheiros da aplicação</a>.

#### Alteração de Dados de Perfil do Conselheiro
A issue do projeto correspondente a desassociação é a <a href="https://github.com/fga-gpp-mds/2017.2-MerendaMais/issues/85">US15 - Marcar os conselheiros como checados ou não checados</a>.

**Comment by SkiaBr23** [comment]
@AllanNobre,

Já fiz o deploy das alterações requisitadas. Peço que testem os _endpoints_ citados acima, já devem estar aceitando apenas as credenciais do **usuário dono do perfil** ou do **responsável pelo aplicativo**.

Aguardo feedback.

**Comment by AllanNobre** [comment]
@SkiaBr23 , 

Vou fazer uns testes usando postman e te mando os resultados aqui.

Muito Obrigado.

**Comment by AllanNobre** [comment]
@SkiaBr23 ,

Testamos aqui a funcionalidade e está funcionando perfeitamente!
Manteremos contato caso surja algum erro!

Muito Obrigado.

**Comment by SkiaBr23** [comment]
@AllanNobre,

Show. Qualquer problema futuro, avisa por aqui via _issue._
