### ISSUE TITLE
Falha de segurança ao desassociar um conselheiro de um Grupo

### ISSUE THREAD

**Issue by AllanNobre** [AppCivicoPlataforma/AppCivico#91]
@SkiaBr23  ,

Encontramos uma falha de segurança ao desassociar um conselheiro de um Grupo, devemos relatar o problema através dessa issue mesmo ou por algum outro meio?

**Comment by SkiaBr23** [comment]
@AllanNobre Sempre por meio de issues se forem problemas técnicos. Manda bala.

**Comment by SkiaBr23** [comment]
@AllanNobre, hoje dei uma olhada e acredito ter encontrado a falha. Acho que se trata da exclusão de membro de um grupo ser feita por qualquer um, certo? Já corrigi esse problema e depois que ajeitar mais uns detalhes publico a alteração, amanhã. Aviso por aqui.

**Comment by AllanNobre** [comment]
@SkiaBr23 , era exatamente esse o problema, fiquei com receio de informar por aqui por ser um ambiente aberto e alguém poder utilizar a brecha de má fé! Obrigado pelo feedback! O fim do semestre é o culpado pela demora na repostas, perdão!

**Comment by SkiaBr23** [comment]
@AllanNobre, publiquei as alterações. O que mudou:

- A criação e exclusão de grupos é restrita ao responsável pelo aplicativo
- A inserção e remoção de um usuário de um grupo é restrita ao responsável pelo aplicativo e ao usuário em questão. Não coloquei apenas para o responsável pois dependendo da aplicação pode ser algo necessário ter mais flexibilidade.

Como está tudo testado estou fechando a issue. Qualquer coisa que apareça, pode reabrir e me avisar por aqui. 

[]'s
