### ISSUE TITLE
Manipulação de postagens através do Master Token da Aplicação 

### ISSUE THREAD

**Issue by AllanNobre** [AppCivicoPlataforma/AppCivico#92]
### Funcionalidade Requisitada
Estou abrindo essa _Issue_ pra deixar registrado o pedido da funcionalidade que diz respeito às permissões de exclusão e **alteração** de uma postagem e seu contéudo serem restritas ao usuário criador em questão **OU** à credencial do responsável pelo aplicativo, sendo possível a utilização do "master _token_ " para que essas ações sejam tomadas por um usuário com permissões mais elevadas. 
@SkiaBr23 , existe alguma previsão de quando estará pronta essa funcionalidade, se for possível implementa-la? Estamos precisando dela com uma certa urgência ;-; .

#### Alterar atributo de um convidado no conteúdo da postagem agendamento 

- A issue do projeto correspondente a confirmar presença no agendamento (alteração de um atributo do conteúdo da postagem) é a <a href="https://github.com/fga-gpp-mds/2017.2-MerendaMais/issues/96">US27 - Confirmar presença no agendamento</a>.

- A issue do projeto correspondente a marcar que um convidado do agendamento já fiscalizou essa visita marcada (alteração de um atributo do conteúdo da postagem) é a <a href="https://github.com/fga-gpp-mds/2017.2-MerendaMais/issues/91">US12 - Encerrar uma fiscalização</a>.

#### Uso do Token master para a exclusão
- Somente para limpar da Nuvem os agendamentos de teste que tem dados inválidos, de modo a limpar a busca por agendamentos com determinado código de determinada postagem.

**Comment by SkiaBr23** [comment]
Olá @AllanNobre!

Amanhã de tarde farei as alterações necessárias. Aviso por aqui.

**Comment by SkiaBr23** [comment]
@AllanNobre,

Fiz as alterações requisitadas e publiquei a versão mais nova. Agora a alteração/exclusão de conteúdos e a exclusão de postagens podem ser efetuadas pelo autor E pelo responsável pelo aplicativo.
Peço que testem o funcionamento na aplicação e mandem um feedback.

Caso ocorra algum problema, favor reabrir a issue.

[]'s

**Comment by AllanNobre** [comment]
@SkiaBr23 ,

Muito obrigado, salvou nossas vidas Kkkk. Vamos testar e qualquer problema nós o informaremos.
OBS: Essas modificações relacionadas ao Token do Responsável pelo App serão atualizadas na documentação da Nuvem?

Valeu!

**Comment by SkiaBr23** [comment]
@AllanNobre a ideia é que sejam atualizadas na documentação após a semana que vem. Até lá podem haver mais alterações, então estou deixando pra atualizar tudo junto.

Obs: Só estarei no TCU novamente na segunda pela manhã, e só posso publicar daqui. Então novas alterações só poderão ser feitas na segunda de manhã.
